### ISSUE TITLE
myAWSIoTMQTTClient.connect() error

### ISSUE THREAD

**Issue by supreethkm** [aws/aws-iot-device-sdk-python#101]
HI,

I got the below error please help me to resolve this error.

> 

AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
Traceback (most recent call last):
  File "basicPubSub.py", line 99, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known 

> 

Thank you

**Comment by hedeshianaws** [comment]
>  socket.gaierror: [Errno -2] Name or service not known

This error means that your hostname is invalid, or that Python is unable to resolve the IoT endpoint you are using. Please make sure your endpoint is valid amd correctly configured, and that your network settings are configured correctly on the host. You can check your environment by issuing getaddrinfo() through the Python interpreter shell.

**Comment by liuszeng** [comment]
Closing due to inactivity.
