### ISSUE TITLE
myAWSIoTMQTTClient.connect()

### ISSUE THREAD

**Issue by shreyasgodbole96** [aws/aws-iot-device-sdk-python#103]
Hi, 

I've below mentioned issue and couldn't find resolve. Please help me with the same! 

Traceback (most recent call last):
  File "my.py", line 14, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/shreyas/project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/shreyas/project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/shreyas/project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/shreyas/project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/shreyas/project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/shreyas/project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 141, in __init__
    ciphers)
ssl.SSLError: [Errno 0] _ssl.c:340: error:00000000:lib(0):func(0):reason(0)

Below is the code for which I'm getting the error

Code:

from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

myAWSIoTMQTTClient = AWSIoTMQTTClient("Thing")
myAWSIoTMQTTClient.configureEndpoint("xxxxxxxxxx.iot.us-west-2.amazonaws.com", 8883)
myAWSIoTMQTTClient.configureCredentials('root-CA.crt', 'Thing.private.key', 'Thing.public.key')

myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1)  
myAWSIoTMQTTClient.configureDrainingFrequency(2)  
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5) 

myAWSIoTMQTTClient.connect()

while True:
	myAWSIoTMQTTClient.publish('hello', "hello", 1)

Thank You!!!

**Comment by liuszeng** [comment]
Hi @shreyasgodbole96 ,

The following line looks suspicious:
```
myAWSIoTMQTTClient.configureCredentials('root-CA.crt', 'Thing.private.key', 'Thing.public.key')
```
If you look at the API doc [here](https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.configureCredentials), you need to input the CA file, private key file and **certificate file**.

Can you switch the "Thing.public.key" to your IoT certificate and try again?

Thanks,
Liusu

**Comment by shreyasgodbole96** [comment]
Changed the things as you said plus created a new thing to avoid any confusion.
But issue not resolved.
Getting same error message written in the previous comment!

Here is the code:

from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

myAWSIoTMQTTClient = AWSIoTMQTTClient("Thing2")
myAWSIoTMQTTClient.configureEndpoint("xxxxxxxx.iot.us-west-2.amazonaws.com", 8883)
myAWSIoTMQTTClient.configureCredentials('root-CA.crt', 'Thing2.private.key', 'Thing2.cert.pem')

# AWSIoTMQTTClient connection configuration
myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1)  
myAWSIoTMQTTClient.configureDrainingFrequency(2)  
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5) 

myAWSIoTMQTTClient.connect()

while True:
	myAWSIoTMQTTClient.publish('hello', "hello", 1)

Thanks in advance

**Comment by liuszeng** [comment]
Hi @shreyasgodbole96 ,

Thanks for providing the detailed information. I would like to confirm the following things:

1. What is the openssl version compiled with Python?
Instructions are available here:
https://github.com/aws/aws-iot-device-sdk-python#minimum-requirements
2. Is the certificate in use activated?
Instructions are available here:
https://docs.aws.amazon.com/iot/latest/developerguide/create-device-certificate.html
3. Is the certificate attached with an IoT policy?
Instructions are available here:
https://docs.aws.amazon.com/iot/latest/developerguide/attach-policy-to-certificate.html

Thanks,
Liusu

**Comment by shreyasgodbole96** [comment]
Hi @liuszeng  Thanks for your valuable inputs I think the problem was with openssl version. I updated the version. 
But now there's a new error 

Traceback (most recent call last):
  File "my.py", line 14, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/shreyas/Project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/shreyas/Project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/shreyas/Project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/shreyas/Project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/shreyas/Project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/shreyas/Project/env/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

myAWSIoTMQTTClient = AWSIoTMQTTClient("Thing")
myAWSIoTMQTTClient.configureEndpoint("xxxxxxxxx.iot.us-west-2.amazonaws.com", 8883)
myAWSIoTMQTTClient.configureCredentials('rootCA.crt', 'Thing.private.key', 'Thing.cert.pem')

# AWSIoTMQTTClient connection configuration
myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myAWSIoTMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5) # 5

myAWSIoTMQTTClient.connect()

while True:
	myAWSIoTMQTTClient.publish('hello', "hello", 1)

Please help me out. Thanks in advance!

**Comment by liuszeng** [comment]
Hi @shreyasgodbole96 ,

It seems that the server certificate is not able to be verified. Can you check your rootCA file and see if it is same as the following?
https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem

Thanks,
Liusu

**Comment by liuszeng** [comment]
Closing due to inactivity.
