### ISSUE TITLE
Unable to update AWS IoT shadow:   ssl.SSLError: unknown error (_ssl.c:3566)

### ISSUE THREAD

**Issue by RubensZimbres** [aws/aws-iot-device-sdk-python#128]
Hello,

I'm collecting telemetry data from my notebook CPU (temperature) and sending to AWS IoT with proper Certificate, Policy and CA.

I'm running a MQTT client from the following Pyhton 3 notebook in my repo:
https://github.com/RubensZimbres/Repo-2018/blob/master/CPU%20Temperature%20-%20IoT%20Project/AWS_Send_test.py

More details of the project at:
https://github.com/RubensZimbres/Repo-2018/tree/master/CPU%20Temperature%20-%20IoT%20Project

However, when I run the notebook via command line, I get the the error:

`2018-05-17 13:58:10,770 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-05-17 13:58:10,770 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-05-17 13:58:10,771 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2018-05-17 13:58:10,771 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2018-05-17 13:58:10,771 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
Traceback (most recent call last):
  File "AWS_Send_test2BEST_QUASE4.py", line 92, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    ciphers=self._tls_ciphers)
  File "/home/rubens/anaconda3/lib/python3.6/ssl.py", line 1149, in wrap_socket
    ciphers=ciphers)
  File "/home/rubens/anaconda3/lib/python3.6/ssl.py", line 745, in __init__
    self._context.load_verify_locations(ca_certs)
ssl.SSLError: unknown error (_ssl.c:3566)
`

My SSL version is 'OpenSSL 1.0.2o  27 Mar 2018' in a Ubuntu 16.04. My rootCA file seems to be ok.

If I remove the command 'myAWSIoTMQTTClient.connect()' the code runs, and according to Cloud Watch, ping the MQTT, sometimes get thing shadow accepted, but does not update the shadow. Sometimes the shadow gets updated, sometimes not.

If I run the notebook without 'myAWSIoTMQTTClient.connect()' I get:

`2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: arn:aws:iot:us-east-1:139115119710:thing/CPUVecto
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-05-17 14:11:01,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2018-05-17 14:11:01,042 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Add new element: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x7ff37e75e2e8>
Temperature: 42 Time (min): 0.0005614082018534343
{"message": {"reported": {"light": "blue", "Temperature": 42, "timestamp": 1526577063.0783799}}, "sequence": 0}
`
I also get well succeeded connections, messages are published, rules executed to CloudWatch, and according to AWS IoT monitor shadows are being updated successfully, although this does not appear always in my CloudWatch.

What can I do regarding these issues ? Thanks in advance.

**Comment by liuszeng** [comment]
Hi @RubensZimbres ,

There are a few things I need your clarifications on:
1. Are you using your own CA or the Symantec root CA for AWS IoT?
1. How are you accessing the shadow? Are you publishing to shadow topics using MQTT client by yourself without using the shadow client provided by the SDK?

Thanks,
Liusu

**Comment by RubensZimbres** [comment]
Hi @liuszeng ,

I generated a CA using Symantec root CA for AWS IoT, in a text file. I sincerely suspect I have to find a openssl command to turn it into a .pem file.

I run the following command line in Linux shell, that runs a basicPubSub.py file adapted to collect CPU telemetry via a command 'sensors' embedded in Python code. 

`python AWS_Send_test.py -e a2thz12345.iot.us-east-1.amazonaws.com -r rootCA.txt -c 6612345-certificate.pem.crt -k 6612345-private.pem.key -id arn:aws:iot:us-east-1:1391112345:thing/CPU-Ubuntu -t '#'
`

I'm not using a MQTT broker like Mosquitto, I'm connecting straight from Linux shell to AWS IoT. I don't know if the Python notebook is invoking the SDK library by using AWSIoTMQTTClient from SDK library. But I'm connecting by myself, so I have also to format the notebook output (JSON) to match the Thing shadow, in this case:

`{"reported": {
    "light": "blue",
    "Temperature": "55",
    "timestamp": 1526323886
  }`

**Comment by liuszeng** [comment]
Hi @RubensZimbres ,

If you are using your own CA, most likely you will be using your own certificate that is signed by your CA. Your CA needs to be registered with AWS IoT. For more details, you can take a look at the following documentation:
https://docs.aws.amazon.com/iot/latest/developerguide/device-certs-your-own.html

SDK provides shadow client that manages the shadow topic subscription and shadow response management for you. Instead of directly using the plain MQTT client, you can use the shadow client instead. We have samples that you can take a look:
https://github.com/aws/aws-iot-device-sdk-python/tree/master/samples/basicShadow
https://github.com/aws/aws-iot-device-sdk-python/tree/master/samples/ThingShadowEcho

Thanks,
Liusu

**Comment by RubensZimbres** [comment]
@liuszeng I followed the instructions at the first link and created:
- rootCA.key
- rootCA.pem
- rootCA.srl
- verificationCert.crt
- verificationCert.csr
- verificationCert.key

After that, I went to AWS IoT panel and uploaded my rootCA.pem and verificationCert.crt and they were accepted. The CA is active. I attached the verificationCert, now 1234567 to the Thing and Politics, and it is active.

But when I run the Ubuntu command line:

`python basicPubSub_adapted.py -e a2t12345.iot.us-east-1.amazonaws.com -r rootCA.pem -c verificationCert.crt -k verificationCert.key -id arn:aws:iot:us-east-1:1312345:thing/CPURubens -t '#'`

I get the following error:

`2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: arn:aws:iot:us-east-1:139115119710:thing/CPUVecto
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-05-18 10:10:23,473 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2018-05-18 10:10:23,474 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
Traceback (most recent call last):
  File "AWS_Send_test2BEST_QUASE4.py", line 92, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/rubens/anaconda3/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    ciphers=self._tls_ciphers)
  File "/home/rubens/anaconda3/lib/python3.6/ssl.py", line 1149, in wrap_socket
    ciphers=ciphers)
  File "/home/rubens/anaconda3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/home/rubens/anaconda3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/home/rubens/anaconda3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
`

**Comment by RubensZimbres** [comment]
@liuszeng I did it. I had to start from the beggining, create a thing, download the certificates, the CA, attach policy, etc.

Thanks a lot for your help
