### ISSUE TITLE
error for the socket.gaierror

### ISSUE THREAD

**Issue by juran321** [aws/aws-iot-device-sdk-python#133]
Hi ,

I wanna connect AWS-IoT using PythongSDK under django framework (in views.py). but when i connect the aws,

it has some bug like:

Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9da9380c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ran/MutantRobotics/src/rovers/Django/django_auth/django_auth/urls.py", line 12, in <module>
    from .views import *
  File "/home/ran/MutantRobotics/src/rovers/Django/django_auth/django_auth/views.py", line 50, in <module>
    myMQTTClient.connect()
  File "/usr/local/lib/python3.5/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python3.5/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/local/lib/python3.5/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/usr/local/lib/python3.5/dist-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/usr/local/lib/python3.5/dist-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.5/dist-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by liuszeng** [comment]
Hi @juran321 ,

`socket.gaierror` means the host name is not able to be resolved, which is usually caused by a misconfiguration in endpoint. Are you able to use the same credentials, host and  port number configuration to run the provided basicPubSub sample?

Samples can be found here:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicPubSub/basicPubSub.py

Thanks,
Liusu

**Comment by juran321** [comment]
Hi Liuzeng,

Thank you for your reply. But I think I use the correct credentials, host, and port number configuration.
like:
```
myMQTTClient = AWSIoTMQTTClient("MutantR_Python")
myMQTTClient.configureEndpoint("abw6d7bh3jzzx.iot.us-west-2.amazonaws.com", 8883)
myMQTTClient.configureCredentials("/home/ran/MutantRobotics/src/rovers/Django/django_auth/django_auth/certs/root-CA.crt","/home/ran/MutantRobotics/src/rovers/Django/django_auth/django_auth/certs/MutantR_Python.private.key","/home/ran/MutantRobotics/src/rovers/Django/django_auth/django_auth/certs/MutantR_Python.cert.pem")
myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline publish
myMQTTClient.configureDrainingFrequency(2)
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(5)
```
And the question is I use the same code in my Beaglebone to pub/sub message in AWS IoT. It's bug free. But this code cannot use my pc's platform in the same time. 
My idea is to connect my pc and my Beaglebone using AWS IoT as middleware.
So, does it mean each endpoint only connect one device?

Thanks a lot!
Ran

**Comment by liuszeng** [comment]
Hi @juran321 ,

Sorry for the delay.

Can you confirm that you are not using the same client id on your Beaglebone and your PC? AWS IoT does not allow 2 clients connect with the same credentials and client id at the same time.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Closing due to inactivity.
