### ISSUE TITLE
SDK is no longer working after v1.4.0 release

### ISSUE THREAD

**Issue by igorescodro** [aws/aws-iot-device-sdk-python#139]
I have a client that connects to AWS IoT and since the v1.4.0 update is no longer working. I tried to run with v1.3.1 and v1.4.0 but neither are working.

Two different errors occurs randomly:

## SSL Error
```
    myMQTTClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:726)
```

## connectTimeoutException
```    myMQTTClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 195, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException
```

I tried to use the [sample provided](https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/jobs/jobsSample.py) with my endpoint and certificates and the same errors occurs:

```
...
2018-06-29 15:19:19,456 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Starting network I/O thread...
2018-06-29 15:19:25,883 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
2018-06-29 15:19:25,883 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 1 sec.
2018-06-29 15:19:25,886 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [disconnect] event
2018-06-29 15:19:25,886 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-06-29 15:19:25,887 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2018-06-29 15:19:25,887 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2018-06-29 15:19:25,887 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2018-06-29 15:19:26,885 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2018-06-29 15:19:26,885 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2018-06-29 15:19:26,885 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2018-06-29 15:19:26,886 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2018-06-29 15:19:29,457 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Connect timed out
Traceback (most recent call last):
  File "jobsSample.py", line 168, in <module>
    jobsClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 1216, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 195, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException
```

**Comment by liuszeng** [comment]
Hi @igorescodro ,

Based on the logs from the jobs sample, it seems that the SDK is getting direct disconnect from the remote server. Which type of authentication are you using, certificate mutual auth. through 8883 or certificate mutual auth. through 443 with ALPN? Can you verify that the policy attached to the certificate has proper permissions?

Thanks,
Liusu

**Comment by igorescodro** [comment]
My client was working fine until Friday, before the SDK update. I tested it today and is working back again. I think there were some kind of update from Amazon side during the weekend.

**Comment by liuszeng** [comment]
Hi @igorescodro ,

Glad to know that the SDK is working for you again.

Unfortunately, due to MQTT protocol characteristics, the SDK is not able to get detailed information from the server about why the connection is failing. Did you by any chance capture the cloudwatch logs? Is it possible for you share a failed request id so that I can forward it back to the service team?

Thanks,
Liusu

**Comment by liuszeng** [comment]
Closing due to inactivity.
