### ISSUE TITLE
Interacting with device shadows sample throws subscribeQueueDisabledException 

### ISSUE THREAD

**Issue by ChittepuVenkat** [aws/aws-iot-device-sdk-python#141]
We are trying out the samples documented as part of module 5(https://docs.aws.amazon.com/greengrass/latest/developerguide/config-dev-subs.html)

We are getting the following exceptions

**Switch:**
Greengrass core has already been discovered.
GGC Host Address: 192.168.1.62
GGC Group CA Path: ./groupCA/root-ca.crt
Private Key of lightController thing Path: 31f6b955b9-private.pem.key
Certificate of lightController thing Path: 31f6b955b9-certificate.pem.crt
Client ID(thing name for lightController): GG_Switch
Target shadow thing ID(thing name for trafficLight): GG_TrafficLight
2018-07-17 17:41:35,238 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-07-17 17:41:35,239 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: GG_Switch
2018-07-17 17:41:35,239 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-07-17 17:41:35,239 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-07-17 17:41:35,239 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
2018-07-17 17:41:35,239 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.100000 sec
2018-07-17 17:41:35,239 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-07-17 17:41:35,240 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-07-17 17:41:35,241 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-07-17 17:41:35,241 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
{"state":{"desired":{"property":"G"}}}
2018-07-17 17:41:35,262 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2018-07-17 17:41:35,262 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2018-07-17 17:41:35,262 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled
Traceback (most recent call last):
  File "lightController.py", line 218, in <module>
    deviceShadowHandler.shadowUpdate(JSONPayload, customShadowCallback_Update, 5)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/shadow/deviceShadow.py", line 356, in shadowUpdate
    self._shadowManagerHandler.basicShadowSubscribe(self._shadowName, "update", self.generalCallback)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/shadow/shadowManager.py", line 70, in basicShadowSubscribe
    self._mqttCoreHandler.subscribe(currentShadowAction.getTopicAccept(), 0, srcCallback)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 274, in subscribe
    self._handle_offline_request(RequestTypes.SUBSCRIBE, (topic, qos, message_callback))
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 345, in _handle_offline_request
    raise self._offline_request_queue_disabled_exceptions[type]
AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeQueueDisabledException

-----------------------
**Light**
Greengrass core has already been discovered.
GGC Host Address: 192.168.1.62
GGC Group CA Path: ./groupCA/root-ca.crt
Private Key of trafficLight thing Path: c8c292e124-private.pem.key
Certificate of trafficLight thing Path: c8c292e124-certificate.pem.crt
Client ID(thing name for trafficLight): GG_TrafficLight
Target shadow thing ID(thing name for trafficLight): GG_TrafficLight
2018-07-17 17:40:56,019 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-07-17 17:40:56,019 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: GG_TrafficLight
2018-07-17 17:40:56,020 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-07-17 17:40:56,020 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-07-17 17:40:56,020 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
2018-07-17 17:40:56,020 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.100000 sec
2018-07-17 17:40:56,020 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-07-17 17:40:56,020 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-07-17 17:40:56,021 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-07-17 17:40:56,041 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2018-07-17 17:41:01,042 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Subscribe timed out
Traceback (most recent call last):
  File "trafficLight.py", line 233, in <module>
    deviceShadowHandler.shadowRegisterDeltaCallback(customShadowCallback_Delta)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/shadow/deviceShadow.py", line 398, in shadowRegisterDeltaCallback
    self._shadowManagerHandler.basicShadowSubscribe(self._shadowName, "delta", self.generalCallback)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/shadow/shadowManager.py", line 68, in basicShadowSubscribe
    self._mqttCoreHandler.subscribe(currentShadowAction.getTopicDelta(), 0, srcCallback)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 281, in subscribe
    raise subscribeTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeTimeoutException

How to overcome this issue.

Thanks and Regards,
Venkat

**Comment by JonathanHenson** [comment]
this looks related to https://github.com/aws/aws-iot-device-sdk-python/issues/7 can you confirm?

**Comment by acoulson2000** [comment]
@ChittepuVenkat, did you ever resolve this issue? I am encountering something similar.

**Comment by towwei** [comment]
i am encountering the same issue as well. if anyone has found a solution, do post here. thanks
