### ISSUE TITLE
Unable to connect a mac to IoT

### ISSUE THREAD

**Issue by aspcompiler** [aws/aws-iot-device-sdk-python#147]
I started by following "connecting device to IOT" wizard in AWS console. I downloaded connect_device_package.zip. However, when I run ./start.sh, I got:

2018-08-12 17:02:29,255 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Event consumer stopped
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 107, in <module>
    myAWSIoTMQTTClient.connect()
  File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

Not sure what it means and how to fix it.

**Comment by JonathanHenson** [comment]
It means the alpn negotiation is failing. Could you possibly show us code for context and an ssldump?
