### ISSUE TITLE
Running basicPubSub sample got "connectTimeoutException"

### ISSUE THREAD

**Issue by 15921050052** [aws/aws-iot-device-sdk-python#148]
Running basicPubSub sample got "connectTimeoutException"
logs here:
```
2018-08-15 16:42:26,665 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2018-08-15 16:42:26,665 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2018-08-15 16:42:27,665 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2018-08-15 16:42:27,666 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2018-08-15 16:42:27,666 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2018-08-15 16:42:27,666 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2018-08-15 16:42:36,618 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Connect timed out
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 107, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/mars/.local/lib/python3.6/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/mars/.local/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 195, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException
```
endpoint : *****.iot.cn-north-1.amazonaws.com.cn

**Comment by 15921050052** [comment]
Policy caused exception.
Closed
