### ISSUE TITLE
gaierror: Dangling threads on unsuccessful connect

### ISSUE THREAD

**Issue by livioso** [aws/aws-iot-device-sdk-python#149]
Subsequent unsuccessful calls of `.connect()` due to `gaierror` seem to cause zombie threads for me:

Example:
```
# keep calling till the connection has been established:
# ...
if not self._mqtt_connected:
  try:
    self._mqtt_connected = self.mqtt.connect()
  except Exception as e:
    logger.exception('Unable to connect to mqtt host')
```

`.connect()` fails with:
```
Traceback (most recent call last):
  File "/home/root/cariot-smartsensor/src/mqtt/interface.py", line 65, in publish
    self._mqtt_connected = self.mqtt.connect()
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

With each unsuccessful call I get a new thread that doesn't seem to be clean up:

```
faulthandler.dump_traceback(file=sys.stderr, all_threads=True)
```

```
Thread 0x6e18f460 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 297 in wait
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 144 in _dispatch
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x6e990460 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 297 in wait
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 144 in _dispatch
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

....

Thread 0x73259460 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 297 in wait
  File "/usr/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 144 in _dispatch
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap
```

*Q: Is this an expected behaviour? If so what's the proper way to handle this?*

**Comment by livioso** [comment]
🙈  Addressed in https://github.com/aws/aws-iot-device-sdk-python/issues/136

**Comment by SantiagoAndre** [comment]
can  you resolve it?
