### ISSUE TITLE
AttributeError: can't set attribute, using ALPN, after upgrade to Python 3.7.0

### ISSUE THREAD

**Issue by johnp789** [aws/aws-iot-device-sdk-python#150]
A small application which worked with previous Python versions failed after an upgrade to Python 3.7.0.  The application uses ALPN to connect to the AWS IoT endpoint.  The error is as follows: 
```
$ ./aws-test.py
Traceback (most recent call last):
  File "./aws-test.py", line 32, in <module>
    myShadowClient.connect(10)
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 1216, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 207, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 119, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 664, in connect
    return self.reconnect()
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 805, in reconnect
    .with_protocol(self._tls_version)\
  File "/usr/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/connection/alpn.py", line 38, in with_protocol
    self._ssl_context.protocol = protocol
AttributeError: can't set attribute
```
I found that commenting out the line `self._ssl_context.protocol = protocol` in `SSLContextBuilder.with_protocol` got my application to work again.  Perhaps the change in Python 3.7 to `SSLContext.wrap_socket` is the reason.

**Comment by JonathanHenson** [comment]
I think this is a regression in later versions of python when setting the protocol (it's read only). We'll look into getting a fix out.

**Comment by graebm** [comment]
We've fixed this internally and we're actively working to release it. I'll post again today or tomorrow once it's available.
