### ISSUE TITLE
AWSIoTPythonSDK.exception.AWSIoTExceptions.disconnectTimeoutException

### ISSUE THREAD

**Issue by a-astakhov** [aws/aws-iot-device-sdk-python#151]
Hi Guys,

I have a lot of data which I need to upload through the publishing messages.

My mqttClient configuration looks like this:

```python
mqttClient = AWSIoTMQTTClient(THING_NAME)
mqttClient.configureEndpoint(ENDPOINT, PORT)
mqttClient.configureCredentials(IOT_ROOT_CA, DEVICE_CERT_KEY, DEVICE_CERT_PEM)
mqttClient.configureAutoReconnectBackoffTime(1, 250, 20)
mqttClient.configureOfflinePublishQueueing(-1)
mqttClient.configureDrainingFrequency(2)
mqttClient.configureConnectDisconnectTimeout(250)
mqttClient.configureMQTTOperationTimeout(5)
```

After 15 successfully published messages I'm getting next error

```
ERROR:AWSIoTPythonSDK.core.protocol.mqtt_core:Disconnect timed out

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 67, in <module>

    result = handler(input['event'], context)
  File "./handler.py", line 70, in main

    postPayload(payload)
  File "./handler.py", line 107, in publish

    mqttClient.disconnect()
  File "./venv/lib/python3.6/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 545, in disconnect

    return self._mqtt_core.disconnect()
  File "./venv/lib/python3.6/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 242, in disconnect

    raise disconnectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.disconnectTimeoutException
```

Has anyone faced with similar issue?

Thanks

**Comment by jackylee1** [comment]
same problem
