### ISSUE TITLE
topic subscribing is not working from today

### ISSUE THREAD

**Issue by warlock-jay** [aws/aws-iot-device-sdk-python#153]
Hi,
I am using awsiotpython sdk in raspberrypi from several months.
i have three systems setted up .
All are working fine till yesterday.
Today they all got same error when they tried to subscribe to iot topics.

Traceback (most recent call last):
  File "Iot_subscribe.py", line 107, in <module>
    iot = createIoT()
  File "Iot_subscribe.py", line 95, in createIoT
    iot.connect(3)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 1216, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
socket.gaierror: [Errno -3] Temporary failure in name resolution

was amazon (aws) changed anything in iot-core servers ?

**Comment by fm-tomh** [comment]
I also lost a few devices today, subscription errors... I'm working on it at the moment but I've got nothing yet.

**Comment by fm-tomh** [comment]
The policy that is automatically generated by AWS  has changed, previously it would allow the Thing to pub/sub to any topic. You now need to specify which ones at it only allows "Topic 1" by default.

**Comment by jay7583** [comment]
actually it started working again without doing anything

**Comment by JonathanHenson** [comment]
This actually looks like a dns outage on the client side. next time this happens, is there any chance you could also run a ping or something and see if DNS resolves. That will tell us if it was related to our dns records or something local to your client and dns settings.

**Comment by JesseJ12345** [comment]
Help, please! Here is a socket.error from greengrasss  documents Model 5:
I am sure do as the doc step by step, but still got this error:

 python trafficLight.py --endpoint xxxxxxxxxxxx-ats.iot.us-west-2.amazonaws.com --rootCA root-ca-cert.pem --ce
rt  .\464eb365b6.cert.pem  --key .\464eb365b6.private.key --thingName GG_TrafficLight --clientId GG_TrafficLight
Greengrass core has already been discovered.
GGC Host Address: 127.0.0.1
GGC Group CA Path: ./groupCA/root-ca.crt
Private Key of trafficLight thing Path: .\464eb365b6.private.key
Certificate of trafficLight thing Path: .\464eb365b6.cert.pem
Client ID(thing name for trafficLight): GG_TrafficLight
Target shadow thing ID(thing name for trafficLight): GG_TrafficLight
2018-10-22 14:35:48,588 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: GG_TrafficLight
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.100000 sec
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
Traceback (most recent call last):
  File "trafficLight.py", line 226, in <module>
    myAWSIoTMQTTShadowClient.connect()
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 1216, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 219, in connect_async
    raise e
socket.error: [Errno 10061] @

**Comment by JesseJ12345** [comment]
Help, please! Here is a socket.error from greengrasss  documents Model 5:
I am sure do as the doc step by step, but still got this error:

 python trafficLight.py --endpoint xxxxxxxxxxxx-ats.iot.us-west-2.amazonaws.com --rootCA root-ca-cert.pem --ce
rt  .\464eb365b6.cert.pem  --key .\464eb365b6.private.key --thingName GG_TrafficLight --clientId GG_TrafficLight
Greengrass core has already been discovered.
GGC Host Address: 127.0.0.1
GGC Group CA Path: ./groupCA/root-ca.crt
Private Key of trafficLight thing Path: .\464eb365b6.private.key
Certificate of trafficLight thing Path: .\464eb365b6.cert.pem
Client ID(thing name for trafficLight): GG_TrafficLight
Target shadow thing ID(thing name for trafficLight): GG_TrafficLight
2018-10-22 14:35:48,588 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: GG_TrafficLight
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-10-22 14:35:48,589 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.100000 sec
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-10-22 14:35:48,591 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-10-22 14:35:48,592 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
Traceback (most recent call last):
  File "trafficLight.py", line 226, in <module>
    myAWSIoTMQTTShadowClient.connect()
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 1216, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 219, in connect_async
    raise e
socket.error: [Errno 10061] @

**Comment by jay7583** [comment]
Hi @JonathanHenson 
I tried pinging .it's getting internet but giving same error.
And it's happening randomly.
i cross checked network speed and connectivity.those are ok.
Are those any other parameters have to check in network?
