### ISSUE TITLE
hey i am getting this error while connecting my pi3 to aws iot 

### ISSUE THREAD

**Issue by aries20** [aws/aws-iot-device-sdk-python#154]
No handlers could be found for logger "AWSIoTPythonSDK.core.protocol.mqtt_core"
Traceback (most recent call last):
  File "awsdht.py", line 22, in <module>
    myMQTTClient.connect()
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 195, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException

**Comment by aries20** [comment]
@graebm  thanks for the reply , I had done exactly the same  what you had written,my start.sh file is working properly but my python code for dht11 is showing the above error  for the below code :

`import RPi.GPIO as GPIO
import dht11
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
from time import sleep
from datetime import date, datetime
 
# initialize GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.cleanup()
 
# AWS IoT certificate based connection
myMQTTClient = AWSIoTMQTTClient("123afhlss456")
myMQTTClient.configureEndpoint("a7dh5l98aa0mw.iot.us-east-2.amazonaws.com", 8883)
myMQTTClient.configureCredentials("/home/pi/cert/CA.pem", "/home/pi/cert/xxxx-private.pem.key", "/home/pi/cert/xxxxx-certificate.pem.crt")
myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec
 
# connect and publish
myMQTTClient.connect()
myMQTTClient.publish("thing01/info", "connected", 0)
 
# loop and publish sensor reading
while 1:
    now = datetime.utcnow()
    now_str = now.strftime('%Y-%m-%dT%H:%M:%SZ')  # e.g. 2016-04-18T06:12:25.877Z
    instance = dht11.DHT11(pin=4)  # BCM GP04
    result = instance.read()
    if result.is_valid():
        payload = '{ "timestamp": "' + now_str + '","temperature": ' + str(result.temperature) + ',"humidity": '+str(result.humidity) + ' }'
        print payload
        myMQTTClient.publish("thing01/data", payload, 0)
        sleep(4)
    else:
        print(".")
        sleep(1)
`

**Comment by gowribkomanduri** [comment]
Hi, did you fix the above mentioned issue with your AWS IoT?

**Comment by Rohitshrimal** [comment]
There are few possible reasons for this.
1. Policy is not attached 
2. Policy does not have the permission to access AWS IoT Core From any Resources (or mention any aws arn,ip). it should be like this 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"  
    },
  ]
}


3. Regions should be same (make sure your thing region and the endpoint region)
4. Network firewall blocking the request.

**Comment by aries20** [comment]
No it doesn’t work

**Comment by Rohitshrimal** [comment]
it worked for me ,
though i can see the above mentioned code where you should put the extension(.crt) of the Root CA Certificate  like "CA.pem.crt".
and also try with this rootCA1 certificate (Just hope you are not using the legacy one)
https://www.amazontrust.com/repository/AmazonRootCA1.pem

**Comment by aries20** [comment]
Ok i will look into it

**Comment by chilu18** [comment]
![image](https://user-images.githubusercontent.com/7957943/55998836-40136580-5cc0-11e9-8c20-c3e7379f8d41.png)

I also seem to be facing similar challenges has anyone had a way around it ?

**Comment by TheoreticallyNick** [comment]
I had this very specific issue, kept on getting a **"No handlers could be found for logger "AWSIoTPythonSDK.core.protocol.mqtt_core""**.

What solved this was adding a policy to the certificate of the device with the following policy code:

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}`

Make sure that "Action:" is "iot:*", and "Resource:" is "*". This allows all incoming messages from the thing.

**Comment by ismjp** [comment]
u mean to say that aws-iot python sdk will not connect now for some time??

**Comment by mahnoushmohammadijahromi** [comment]
I have the same issue, this is the policy that I'm using:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}
```
and yet I'm getting the same error:

```
Connect timed out
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "mqtt_bridge.py", line 79, in on_message
    publish_to_sensorup(payload,TOPIC)
  File "mqtt_bridge.py", line 41, in publish_to_sensorup
    myAWSIoTMQTTClient.connect()
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/Users/mahnoushjahromi/opt/anaconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 199, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException
```

**Comment by jmklix** [comment]
@mahnoushmohammadijahromi it looks like you might be getting a different error. Please open a new issue with details of your current error.
