### ISSUE TITLE
Suddenly getting "Offline request detected"

### ISSUE THREAD

**Issue by acoulson2000** [aws/aws-iot-device-sdk-python#157]
This issue seems similar to #7 , but I have been unable to resolve it.

When I try to launch the trafficLight.py script from the greengrass samples, using my own Thing, I keep getting the following:
`key ExampleBlower.private.key --thingName ExampleBlower --clientId ExampleBlower
Greengrass core has already been discovered.
GGC Host Address: 192.168.13.75
GGC Group CA Path: ./groupCA/root-ca.crt
Private Key of trafficLight thing Path: ExampleBlower.private.key
Certificate of trafficLight thing Path: ExampleBlower.cert.pem
Client ID(thing name for trafficLight): ExampleBlower
Target shadow thing ID(thing name for trafficLight): ExampleBlower
2018-09-04 17:39:17,868 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-09-04 17:39:17,870 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: ExampleBlower
2018-09-04 17:39:17,871 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-09-04 17:39:17,873 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-09-04 17:39:17,874 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
2018-09-04 17:39:17,875 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.100000 sec
2018-09-04 17:39:17,876 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-09-04 17:39:17,878 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-09-04 17:39:17,879 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-09-04 17:39:17,880 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-09-04 17:39:17,881 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-09-04 17:39:17,883 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-09-04 17:39:17,884 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-09-04 17:39:17,887 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-09-04 17:39:17,888 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-09-04 17:39:17,889 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-09-04 17:39:17,891 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-09-04 17:39:18,054 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2018-09-04 17:39:18,054 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2018-09-04 17:39:18,055 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled
Traceback (most recent call last):
  File "trafficLight.py", line 232, in <module>
    deviceShadowHandler.shadowRegisterDeltaCallback(customShadowCallback_Delta)
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\shadow\deviceShadow.py", line 398, in shadowRegisterDelt
aCallback
    self._shadowManagerHandler.basicShadowSubscribe(self._shadowName, "delta", self.generalCallback)
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\shadow\shadowManager.py", line 68, in basicShadowSubscri
be
    self._mqttCoreHandler.subscribe(currentShadowAction.getTopicDelta(), 0, srcCallback)
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 295, in subscribe
    self._handle_offline_request(RequestTypes.SUBSCRIBE, (topic, qos, message_callback))
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 366, in _handle_offline_req
uest
    raise self._offline_request_queue_disabled_exceptions[type]
AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeQueueDisabledException`

I understand this may be due to the client not being connected when the shadow delta subscription is performed, but I don't understand why the client would be disconnected - this is the unmodified sample code. I am currently only connecting with a single client. I have even completely re-built the thing, downloaded new cert & key, rebuilt the core and re-deployed. Same error.
Is there any way to troubleshoot why the disconnect might be happening?

**Comment by acoulson2000** [comment]
Weird...when I turn DEBUG level logging on, I always get a "Subsribe timed out"

`2018-09-04 18:03:20,274 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-09-04 18:03:20,277 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2018-09-04 18:03:20,277 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2018-09-04 18:03:20,278 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2018-09-04 18:03:20,471 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Starting network I/O thread...
2018-09-04 18:03:20,474 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
2018-09-04 18:03:20,474 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
2018-09-04 18:03:20,475 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - No need for recovery
2018-09-04 18:03:20,477 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-09-04 18:03:20,478 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2018-09-04 18:03:20,479 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Adding a new subscription record: $aws/things/ExampleBlower/shadow/update/del
ta qos: 0
2018-09-04 18:03:20,478 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [disconnect] event
2018-09-04 18:03:20,478 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
2018-09-04 18:03:20,482 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom suback event callback...
2018-09-04 18:03:20,486 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 1 sec.
2018-09-04 18:03:20,487 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-09-04 18:03:21,653 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
2018-09-04 18:03:21,653 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
2018-09-04 18:03:21,656 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Has recovery job
2018-09-04 18:03:21,659 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Start resubscribing
2018-09-04 18:03:21,659 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-09-04 18:03:21,660 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
2018-09-04 18:03:21,661 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [disconnect] event
2018-09-04 18:03:21,662 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 2 sec.
2018-09-04 18:03:21,663 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-09-04 18:03:23,855 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
2018-09-04 18:03:23,855 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
2018-09-04 18:03:23,857 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Has recovery job
2018-09-04 18:03:23,860 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Start resubscribing
2018-09-04 18:03:23,860 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-09-04 18:03:23,861 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
2018-09-04 18:03:23,861 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [disconnect] event
2018-09-04 18:03:23,862 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 4 sec.
2018-09-04 18:03:23,863 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2018-09-04 18:03:25,495 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Removing custom event callback...
2018-09-04 18:03:25,496 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Subscribe timed out
Traceback (most recent call last):
  File "trafficLight.py", line 232, in <module>
    deviceShadowHandler.shadowRegisterDeltaCallback(customShadowCallback_Delta)
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\shadow\deviceShadow.py", line 398, in shadowRegisterDelt
aCallback
    self._shadowManagerHandler.basicShadowSubscribe(self._shadowName, "delta", self.generalCallback)
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\shadow\shadowManager.py", line 68, in basicShadowSubscri
be
    self._mqttCoreHandler.subscribe(currentShadowAction.getTopicDelta(), 0, srcCallback)
  File "C:\Users\acoulson\AppData\Local\Programs\Python\Python37\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 302, in subscribe
    raise subscribeTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeTimeoutException`

Seems like may the logging affects the timing a bit. If I interpret this right, there IS a disconnect event coming through...still have no idea why, though.

**Comment by JonathanHenson** [comment]
Theres a couple of things going on here, most of which we'd need a packet trace to track down.

One possibility is that authentication is failing at the server. Have you checked the policy configuration for your certificate?

Another possibility is that your connection is being lost in a firewall somewhere. Have you verified the traffic can get through to the configured port?

**Comment by acoulson2000** [comment]
I feel like the authentication was OK, since if I intentionally pointed it to a bad cert or key, I would get a different error that was related to SSL authentication.

I ruled out connectivity issues by running the same script on the ggc device (a Pi) itself - same result.

Finally, I blew away the Group in the AWS console, completely re-configured it from scratch, re-uploaded the config to the Pi and restarted. That worked. 

It would sure be nice if there was more logging somewhere that provided some indication of what's going on in these situations. If the client is being actively disconnected, surely the server could log something when it's going to disconnect a client?

**Comment by cnrmck** [comment]
+1 I'm having this issue too.

**Comment by cnrmck** [comment]
I will try the AWS Group solution. Right now, I'm just incredibly frustrated that this is such a difficult error to track. Please address

**Comment by goliatone** [comment]
Just as a reference for those landing here through a search engine, I had the same issue and solved it by changing the attached policy to something more permissive and in my case that enabled my device to communicate successfully.

**Comment by claytantor** [comment]
Have yoy tries tracing the connect lifecycle for your call path. This can happen if you dont successfully make sure to call `myMQTTClient.connect()` prior to your publish or subscribe.

**Comment by nolex90** [comment]
Any update on this?
I experience the same things.

**Comment by bretambrose** [comment]
This is a pretty old thread with several different behaviors described in it.  Can you open up a new issue and add as much information as you can?  Are you able to run run the samples?  What is your device policy (masked if necessary)?  Do you have a debug log you can share?

**Comment by JesseJ12345** [comment]
I had the same issue **"Offline request detected"** , at first, the connecting is ok, then the communication is ok, after a while(maybe 30minutes, maybe 20h) this happened randomly.
I captured logs as following, it show encrypted alert 21, and then reconnect ... 

Could anyone have ideas ?  thanks.

![image](https://user-images.githubusercontent.com/31585302/89401743-5ad8db80-d748-11ea-82fa-806d5e64b582.png)

**Comment by jmklix** [comment]
Closing this as it is an older issue. As mentioned above please open a new issue with the details about your question
