### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by cshurt64** [aws/aws-iot-device-sdk-python#165]
Hello all,
first off I'm new to AWS and a fairly novice Python programmer.  I've been trying to run basicPubSub but without success as of yet.  I'm running on Windows 7 and I'm using Python 2.7.11 (SSL version 1.0.2d Jul 2015).  I have gone through the basic steps of creating a Thing in AWS console.  I have also create a Certificate and attached a Policy to it. I am using the Amazon Root CA 3. When I run basicPubSub I get the following output.  

C:\Users\churt\AWS-Samples\aws-iot-device-sdk-python-master\samples\basicPubSub>python basicPubSub.py -e a7wk8pv5b3fxc-ats.iot.us-east-1.amazonaws.com -r AmazonRootCA3.pem -c 9b58ab52f9-certificate.pem.crt -k 9b58ab52f9-private.pem.key > error.txt
2018-10-09 19:03:03,092 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2018-10-09 19:03:03,102 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2018-10-09 19:03:03,102 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-10-09 19:03:03,105 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: basicPubSub
2018-10-09 19:03:03,111 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-10-09 19:03:03,118 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-10-09 19:03:03,131 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-10-09 19:03:03,138 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-10-09 19:03:03,154 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-10-09 19:03:03,163 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-10-09 19:03:03,168 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-10-09 19:03:03,181 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-10-09 19:03:03,187 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2018-10-09 19:03:03,201 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2018-10-09 19:03:03,220 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-10-09 19:03:03,223 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-10-09 19:03:03,236 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-10-09 19:03:03,255 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-10-09 19:03:03,256 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-10-09 19:03:03,285 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2018-10-09 19:03:03,290 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2018-10-09 19:03:03,298 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2018-10-09 19:03:03,871 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2018-10-09 19:03:03,872 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2018-10-09 19:03:03,875 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2018-10-09 19:03:03,880 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2018-10-09 19:03:03,885 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2018-10-09 19:03:03,897 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2018-10-09 19:03:03,903 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2018-10-09 19:03:03,915 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Waiting for event consumer to completely stop
2018-10-09 19:03:03,921 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Event consumer stopped
Traceback (most recent call last):
  File "basicPubSub.py", line 107, in <module>
    myAWSIoTMQTTClient.connect()
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "C:\Python27\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 219, in connect_async
    raise e
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Any help would be appreciated.

**Comment by cshurt64** [comment]
Was able to resolve the above issue by using [AmazonRootCA1.pem](https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html#server-authentication), not sure why this is the case, but it allowed me to move forward.

**Comment by anikey-m** [comment]
Just discovered new endpoints (Amazon Trust Services Endpoints) and encountered the same problem. Everything work good with [Amazon Root CA 1](https://www.amazontrust.com/repository/AmazonRootCA1.pem), but other 3 root certs throw ssl error:
```
...
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 207, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 119, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 664, in connect
    return self.reconnect()
  File "/home/anikey/.local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 824, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib64/python3.7/ssl.py", line 1222, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs
  File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)
 ```
I dig little dipper with openssl and find out that aws endpoint always return [Amazon Root CA 1](https://www.amazontrust.com/repository/AmazonRootCA1.pem) certificate, that`s why verification with other certificates fails.
Next i found [this guide](https://aws.amazon.com/blogs/iot/elliptic-curve-cryptography-and-forward-secrecy-support-in-aws-iot-3/) about ECC client certs and try to repeat it. And it works for old endpoint with VeriSign cert but have problems with new (ATS) endpoint: 
1. `handshake failure` when `--ciphers ECDHE-ECDSA-AES128-GCM-SHA256` specified;
2. `certificate verify failed` with 2, 3 and 4 cert - actually expected behaviour;
3. success publish with 1 cert.

As I know, cipher suite selection in tls happen at very beginning of handshake before any certificate transmitting. Type of client certificate should not affect on server certificate selection algorithm. Correct me if it is not.

I can't find any documentation about usage of RSA 4096 (2), ECC 256 (3) and ECC 384 (4) server certificates. Any tips?

**Comment by anikey-m** [comment]
Found official answer on AWS Developer Forum: https://forums.aws.amazon.com/message.jspa?messageID=870009#870009.

Short answer: for now on the ATS endpoints works only Amazon Root CA 1.
