### ISSUE TITLE
AWSIot with Raspberry : Problem ssl.SSLError: unknown error (_ssl.c:2947)

### ISSUE THREAD

**Issue by coidien** [aws/aws-iot-device-sdk-python#166]
Hi, 

I connect my Raspberry to AWSIoT to send data from Temperatur sensor, but i have Always this Problem:  

_Traceback (most recent call last):
  File "temp_LCD_AWS1.py", line 23, in <module>
    myMQTTClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
ssl.SSLError: unknown error (_ssl.c:2947)_

i am using Python 2.7, openssl 1.1.0.

do anyone know how to fix this ???

at first i think there ist Problem with certificate, that i use my Laptop with mqttfx to connect and it is okie.
I read another Thread, that may be Problem with Python 2.7 not support TLS Version 1.2, but i do not know how to fix that. Update and Upgrade Rasbian, Python, Openssl...I do all.  *___*

**Comment by cnrmck** [comment]
@coidien Could you share the code that you are using?
