### ISSUE TITLE
AWS IoT - RPi connectivity error - No handlers could be found for logger "AWSIoTPythonSDK.core.protocol.mqtt_core

### ISSUE THREAD

**Issue by gowribkomanduri** [aws/aws-iot-device-sdk-python#173]
I have written a python code to ingest Ultrasonic sensor data into AWS IoT through RPi controller. The code runs fine for initial 10 to 15 values on AWS IoT and then i get a error in python interprettor as:
No handlers could be found for logger "AWSIoTPythonSDK.core.protocol.mqtt_core"

Traceback (most recent call last):
  File "/home/pi/KesteIoTDemo20181027/RPi_Ultrasonic_AWSIoT", line 68, in <module>
    mqttConfiguration()
  File "/home/pi/KesteIoTDemo20181027/RPi_Ultrasonic_AWSIoT", line 57, in mqttConfiguration
    myMQTTClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 195, in connect
    raise connectTimeoutException()
connectTimeoutException

The python code is as below:

#!/usr/bin/python
#Libraries
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient #Import from AWS-IoT Library
import RPi.GPIO as GPIO
import time
from datetime import date, datetime #To get date and time

myMQTTClient = AWSIoTMQTTClient("new_Client")

#GPIO Mode (BOARD / BCM)
GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.cleanup()

#set GPIO Pins
PIN_TRIGGER = 7
PIN_ECHO = 11
#set GPIO direction (IN / OUT)
GPIO.setup(PIN_TRIGGER, GPIO.OUT)
GPIO.setup(PIN_ECHO, GPIO.IN)

# Waiting for sensor to settle
GPIO.output(PIN_TRIGGER, GPIO.LOW)
time.sleep(5)

def distance():
    # set Trigger to HIGH
    GPIO.output(PIN_TRIGGER, GPIO.HIGH)
    # set Trigger after 0.01ms to LOW
    time.sleep(0.00001)
    GPIO.output(PIN_TRIGGER, GPIO.LOW)
    # save StartTime
    while GPIO.input(PIN_ECHO)==0:
        pulse_start_time = time.time()
    # save time of arrival
    while GPIO.input(PIN_ECHO)==1:
        pulse_end_time = time.time()
    # time difference between start and arrival
    pulse_duration = pulse_end_time - pulse_start_time
    distance = round(pulse_duration * 17150, 2)
    #print distance
    return distance
    GPIO.cleanup()

# function definition for MQTT connection
def mqttConfiguration():
    # MQTT Communication Module: Ingest data into AWS IoT
            
            myMQTTClient.configureEndpoint("a39io8xlqtnhq2-ats.iot.us-east-1.amazonaws.com", 8883)
            myMQTTClient.configureCredentials("/home/pi/KesteIoTDemo20181027/X509CARoot.crt", "/home/pi/KesteIoTDemo20181027/61fc39dec3-private.pem.key", "/home/pi/KesteIoTDemo20181027/61fc39dec3-certificate.pem.crt")
            myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
            myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
            myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
            myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec
            connecting_time = time.time() + 10
            if time.time() < connecting_time:  #try connecting to AWS for 10 seconds
                myMQTTClient.connect()
                myMQTTClient.publish("UltrasonicSensor1/data", "connected", 0)
                print "MQTT Client connection success!"
            else:
                print "Error: Check your AWS details in the program"
    
if __name__ == '__main__':
    try:
        while True:
            dist = 0
            dist = distance()
            mqttConfiguration()
            # Publishing the topic "TrashCan/Status"
            now = datetime.utcnow() #get date and time 
            current_time = now.strftime('%Y-%m-%dT%H:%M:%SZ') #get current time in string format
            #prepare the payload in string format
            payload = '{ "timestamp": "' + current_time + '","Distance "' + str(dist)  + ' }'
            #print payload on python intrepettor for local reference
            print payload
            #publish the actual payload on AWS IoT
            myMQTTClient.publish("UltrasonicSensor/data", payload, 0) #publish the payload
            time.sleep(2) #Wait for 2 sec then update the next value

            
        # Reset by pressing CTRL + C
    except KeyboardInterrupt:
        print("Measurement stopped by User")
        GPIO.cleanup()
#######################################################################

Can any body please advise on how to fix this?

I have already checked the AWS policy attached to my certificate which has been given full IoT access

**Comment by gowribkomanduri** [comment]
#154
