### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

### ISSUE THREAD

**Issue by jackygao2018** [aws/aws-iot-device-sdk-python#184]
Hello All,

I've got the following error log that worked fine at last few days of 2018 when I tried to connect to AWSIOT today.
I'm running on MAC and I'm using Python 3.7 (OpenSSL 1.0.2q  20 Nov 2018).
And i am using IAM credentials.
And I am using the CA in this link: https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem
Can anyone help me to resolve this issue? Many thanks in advance!

**The error logs are as following:**
Traceback (most recent call last):

    self.myAWSIoTMQTTClient.connect()
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 207, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 119, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 664, in connect
    return self.reconnect()
  File "/Users/jgao/Library/Python/3.7/lib/python/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    rawSSL = ssl.wrap_socket(sock, ca_certs=self._tls_ca_certs, cert_reqs=ssl.CERT_REQUIRED)  # Add server certificate verification
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1213, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

Process finished with exit code 1

**Comment by graebm** [comment]
Version 1.4.2 is now available via pip. Be sure to install like so `pip install AWSIoTPythonSDK==1.4.2` to ensure you get the latest version.
