### ISSUE TITLE
SSL Error: SSL PEM lib

### ISSUE THREAD

**Issue by Thaiph1308** [aws/aws-iot-device-sdk-python#195]
I'm following this instruction:
**JobsSample**
`> python jobsSample.py -e <endpoint> -r <rootCAFilePath> -c <certFilePath> -k <privateKeyFilePath> -n <thingName>`
With rootCA i take from:
`https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem`
Here is the output when I run the script with rootCA above and Certfile + Private take from AWS:
`python jobsSample.py -e <endpoint> -r <rootCAFilePath> -c <certFilePath> -k <privateKeyFilePath> -n <thingName>`
```
2019-04-09 19:05:29,922 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2019-04-09 19:05:29,923 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2019-04-09 19:05:29,924 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2019-04-09 19:05:29,924 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: basicJobsSampleClient
2019-04-09 19:05:29,924 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2019-04-09 19:05:29,925 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2019-04-09 19:05:29,925 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2019-04-09 19:05:29,925 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2019-04-09 19:05:29,926 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2019-04-09 19:05:29,926 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2019-04-09 19:05:29,926 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2019-04-09 19:05:29,927 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2019-04-09 19:05:29,927 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2019-04-09 19:05:29,927 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 10.000000 sec
Connecting to MQTT server and setting up callbacks...
2019-04-09 19:05:29,928 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2019-04-09 19:05:29,928 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2019-04-09 19:05:29,928 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2019-04-09 19:05:29,929 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2019-04-09 19:05:29,929 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2019-04-09 19:05:29,930 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2019-04-09 19:05:29,971 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2019-04-09 19:05:29,972 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2019-04-09 19:05:29,972 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2019-04-09 19:05:29,972 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2019-04-09 19:05:29,973 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2019-04-09 19:05:29,973 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2019-04-09 19:05:29,973 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Waiting for event consumer to completely stop
2019-04-09 19:05:29,980 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2019-04-09 19:05:29,981 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Event consumer stopped
Traceback (most recent call last):
  File "jobsSample.py", line 168, in <module>
    jobsClient.connect()
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 1216, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
ssl.SSLError: [SSL] PEM lib (_ssl.c:2699)
```
I'm using **Python 2.7** and SSL Version **'OpenSSL 1.1.0j  20 Nov 2018'**
Can anyone help me to resolve this issue? Many thanks in advance!

**Comment by Thaiph1308** [comment]
> You have to check your endpoint. Current, AWS IoT provide 2-endpoint if you use -ats endpoint, is that case you have to use root-CA for -ats.
> https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html#server-authentication
> 
> Why AWS IoT Core provide 2-endpoint? detail is here.
> https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/

Thank you for your reply, with -ats endpoint only Amazon Root CA 1 worked, the others (CA 2-3-4) do not work.

**Comment by ColdenCullen** [comment]
Glad you found a solution!
