### ISSUE TITLE
Event consumer stopped

### ISSUE THREAD

**Issue by freetime312** [aws/aws-iot-device-sdk-python#214]
> bash start.sh 

Running pub/sub sample application...
2019-07-04 10:42:07,641 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2019-07-04 10:42:07,644 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2019-07-04 10:42:07,645 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2019-07-04 10:42:07,646 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: basicPubSub
2019-07-04 10:42:07,647 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2019-07-04 10:42:07,648 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2019-07-04 10:42:07,650 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2019-07-04 10:42:07,651 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2019-07-04 10:42:07,652 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2019-07-04 10:42:07,653 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2019-07-04 10:42:07,655 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2019-07-04 10:42:07,656 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2019-07-04 10:42:07,657 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2019-07-04 10:42:07,658 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2019-07-04 10:42:07,660 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2019-07-04 10:42:07,661 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2019-07-04 10:42:07,662 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2019-07-04 10:42:07,663 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2019-07-04 10:42:07,664 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2019-07-04 10:42:07,667 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2019-07-04 10:42:07,668 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2019-07-04 10:42:07,670 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2019-07-04 10:42:08,583 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2019-07-04 10:42:08,585 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2019-07-04 10:42:08,586 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2019-07-04 10:42:08,588 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2019-07-04 10:42:08,591 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2019-07-04 10:42:08,593 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2019-07-04 10:42:08,589 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2019-07-04 10:42:08,595 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Waiting for event consumer to completely stop
2019-07-04 10:42:08,596 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Event consumer stopped
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 107, in <module>
    myAWSIoTMQTTClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 223, in connect_async
    raise e
socket.error: [Errno 104] Connection reset by peer

**Comment by freetime312** [comment]
Is this a AWS connect refused?

**Comment by bretambrose** [comment]
It seems very likely.  What is the context?  Are you just running the connection kit sample?

**Comment by freetime312** [comment]
> It seems very likely. What is the context? Are you just running the connection kit sample?
Thanks. My company network not permit me to visit AWS.
