### ISSUE TITLE
Unable to connect, socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by j-cripps** [aws/aws-iot-device-sdk-python#231]
Hi,

Trying to run the pubSub example code but I cannot connect, debug log plus exception listed below. Running on fresh install Debian on raspberry pi.

```
2019-11-26 21:27:30,926 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2019-11-26 21:27:30,930 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2019-11-26 21:27:30,931 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2019-11-26 21:27:30,931 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: RasPiTempMonitor
2019-11-26 21:27:30,932 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2019-11-26 21:27:30,932 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2019-11-26 21:27:30,933 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2019-11-26 21:27:30,933 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2019-11-26 21:27:30,934 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2019-11-26 21:27:30,935 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2019-11-26 21:27:30,936 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2019-11-26 21:27:30,936 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2019-11-26 21:27:30,937 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2019-11-26 21:27:30,938 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2019-11-26 21:27:30,938 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2019-11-26 21:27:30,939 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2019-11-26 21:27:30,939 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2019-11-26 21:27:30,940 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2019-11-26 21:27:30,940 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2019-11-26 21:27:30,942 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2019-11-26 21:27:30,943 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2019-11-26 21:27:30,944 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2019-11-26 21:27:30,948 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2019-11-26 21:27:30,949 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2019-11-26 21:27:30,949 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2019-11-26 21:27:30,950 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2019-11-26 21:27:30,950 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2019-11-26 21:27:30,951 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2019-11-26 21:27:30,951 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Waiting for event consumer to completely stop
2019-11-26 21:27:30,952 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2019-11-26 21:27:30,953 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Event consumer stopped
Traceback (most recent call last):
  File "awsTemp.py", line 64, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/pi/AWSIoTPythonSDK/MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/pi/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/pi/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 223, in connect_async
    raise e
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by graebm** [comment]
It looks like the socket was unable to find the host by name ([socket docs](https://docs.python.org/3/library/socket.html#socket.gaierror)). Specifically, you're are getting the `EAI_NONAME` error.

Are you sure you are passing the endpoint address correctly? It should look something like: `abcdefgh012345-ats.iot.us-west-2.amazonaws.com`
