### ISSUE TITLE
No topic specified, or incorrect topic type

### ISSUE THREAD

**Issue by nitrogear** [aws/aws-iot-device-sdk-python#232]
I'm trying test jobsSample.py to register a thing in IoT. When I execute:

`python aws-iot-device-sdk-python/samples/jobs/jobsSample.py -e xxx.iot.us-east-1.amazonaws.com -r root-CA.crt -c python-jobs-client-01.cert.pem -k python-jobs-client-01.private.key -id python`

I get an error:

```
Connecting to MQTT server and setting up callbacks...
2019-12-17 23:19:54,915 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2019-12-17 23:19:54,916 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2019-12-17 23:19:54,916 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2019-12-17 23:19:54,917 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2019-12-17 23:19:54,917 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2019-12-17 23:19:54,917 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2019-12-17 23:19:55,360 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Starting network I/O thread...
2019-12-17 23:19:55,542 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
2019-12-17 23:19:55,544 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
2019-12-17 23:19:55,544 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - No need for recovery
2019-12-17 23:19:55,544 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2019-12-17 23:19:55,578 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2019-12-17 23:19:55,579 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Adding a new subscription record: None qos: 1
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/jobs/jobsSample.py", line 169, in <module>
    jobsMsgProc = JobsMessageProcessor(jobsClient, clientId)
  File "aws-iot-device-sdk-python/samples/jobs/jobsSample.py", line 40, in __init__
    self._setupCallbacks(self.awsIoTMQTTThingJobsClient)
  File "aws-iot-device-sdk-python/samples/jobs/jobsSample.py", line 43, in _setupCallbacks
    self.awsIoTMQTTThingJobsClient.createJobSubscription(self.newJobReceived, jobExecutionTopicType.JOB_NOTIFY_NEXT_TOPIC)
  File "/usr/local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 1589, in createJobSubscription
    return self._AWSIoTMQTTClient.subscribe(topic, self._QoS, callback)
  File "/usr/local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 696, in subscribe
    return self._mqtt_core.subscribe(topic, QoS, callback)
  File "/usr/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 302, in subscribe
    rc, mid = self._subscribe_async(topic, qos, self._create_blocking_ack_callback(event), message_callback)
  File "/usr/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 321, in _subscribe_async
    rc, mid = self._internal_async_client.subscribe(topic, qos, ack_callback)
  File "/usr/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 186, in subscribe
    rc, mid = self._paho_client.subscribe(topic, qos)
  File "/usr/local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 1107, in subscribe
    raise ValueError("No topic specified, or incorrect topic type.")
ValueError: No topic specified, or incorrect topic type.
```

Is it because of missing policies or why?

**Comment by nitrogear** [comment]
My bad, I didn't pass thingName as a parameter
