### ISSUE TITLE
Trouble in offline queue disabling 

### ISSUE THREAD

**Issue by MickaelDelanoe** [aws/aws-iot-device-sdk-python#236]
I would like disable the MQTT offline queue, so I use `configureOfflinePublishQueueing(0)`method from `AWSIoTMQTTClient object`.
Unfortunately, it does not woks, messages still "store" in the mqtt queue and I do not have the exception `publishQueueDisabledException` after publishing messages.

__Env used:__
- Python 2.7.11
- AWSIoTPythonSDK : 1.3.1

__For MQTT:__
- Authentication : By certificates
- Sync functions

__Source code__
The global code of the application is quite complex, so to debug this issue I work with the next code, directly in the terminal of my IoT.

```python
import AWSIoTPythonSDK.MQTTLib as AWSIoTPyMQTT
from AWSIoTPythonSDK.exception.AWSIoTExceptions import publishQueueDisabledException
import sys, os, json
myAWSIoTMQTTClient = AWSIoTPyMQTT.AWSIoTMQTTClient("<ClientID>")
myAWSIoTMQTTClient.configureEndpoint("<awsBrokerURL>", 8883)
myAWSIoTMQTTClient.configureCredentials("/storage/certificates/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem", "/storage/certificates/<ClientID>/<shortID>-private.pem.key", "/storage/certificates/<ClientID>/<shortID>-certificate.pem.crt")
 
 
myAWSIoTMQTTClient.configureOfflinePublishQueueing(0)
#myAWSIoTMQTTClient.configureDrainingFrequency(2)
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)
myAWSIoTMQTTClient.connect()
 
def print_errors(client, userdata, message):
    serverError = json.loads(message.payload)
    print serverError
 
 
myAWSIoTMQTTClient.subscribe('stage/<ClientID>/<authToken>/measures/error', 1, print_errors)
 
myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
```

Exemple
```
Python 2.7.11 (default, Feb  6 2019, 19:32:43) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import AWSIoTPythonSDK.MQTTLib as AWSIoTPyMQTT
>>> from AWSIoTPythonSDK.exception.AWSIoTExceptions import publishQueueDisabledException
>>> import sys, os, json
>>> myAWSIoTMQTTClient = AWSIoTPyMQTT.AWSIoTMQTTClient("<ClientID>")
>>> myAWSIoTMQTTClient.configureEndpoint("<awsBrokerURL>", 8883)
>>> myAWSIoTMQTTClient.configureCredentials("/storage/certificates/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem", "/storage/certificates/<ClientID>/<shortID>-private.pem.key", "/storage/certificates/<ClientID>/<shortID>-certificate.pem.crt")
>>> 
>>> 
>>> myAWSIoTMQTTClient.configureOfflinePublishQueueing(0)
>>> myAWSIoTMQTTClient.configureDrainingFrequency(2)
>>> myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)
>>> myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)
>>> myAWSIoTMQTTClient.connect()
True
>>> def print_errors(client, userdata, message):
...     serverError = json.loads(message.payload)
...     print serverError
... 
>>> 
>>> myAWSIoTMQTTClient.subscribe('stage/<ClientID>/<authToken>/measures/error', 1, print_errors)
True
>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
True
>>> {u'isCustom': True, u'errors': [{u'field': u'payload.data', u'message': u'"data" is required', u'code': u'required'}], u'code': 400, u'type': u'Payload', u'name': u'ValidateError'}
>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
True
>>> {u'isCustom': True, u'errors': [{u'field': u'payload.data', u'message': u'"data" is required', u'code': u'required'}], u'code': 400, u'type': u'Payload', u'name': u'ValidateError'}
>>> 
```

- The connection works (rep: True)
- The suscription on the topic '…./measures/error' works (rep: True)
- Messages sending works
- Our Server service return an error according wrong payload format (but is not the purpose)

But any `publishQueueDisabledException` raising, do you know why ?
I should have an `publishQueueDisabledException`, isn't it ?

**Comment by KaibaLopez** [comment]
Hi @MickaelDelanoe ,
I'll look more into this, but yea the idea is that you'd get a publishQueueDisabledException()... could you turn on the logger and let me know what it shows?
It looks like you know what to look for there but in essence, I'd like to know where it deviates and the sdk has clear logs for that.

**Comment by MickaelDelanoe** [comment]
Thanks for your return.
I used the next logger, I hop is that what you means by "turn on the logger"

```python
logger = logging.getLogger("AWSIoTPythonSDK.core")
logger.setLevel(logging.DEBUG)
streamHandler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
streamHandler.setFormatter(formatter)
logger.addHandler(streamHandler)
```


__Result__ :
```python
Python 2.7.11 (default, Feb  6 2019, 19:32:43) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import AWSIoTPythonSDK.MQTTLib as AWSIoTPyMQTT
>>> from AWSIoTPythonSDK.exception.AWSIoTExceptions import publishQueueDisabledException
>>> import sys, os, json
>>> import logging
>>> 
>>> logger = logging.getLogger("AWSIoTPythonSDK.core")
>>> logger.setLevel(logging.DEBUG)
>>> streamHandler = logging.StreamHandler()
>>> formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
>>> streamHandler.setFormatter(formatter)
>>> logger.addHandler(streamHandler)
>>> 
>>> myAWSIoTMQTTClient = AWSIoTPyMQTT.AWSIoTMQTTClient("<ClientID>")
2020-01-16 09:55:46,138 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2020-01-16 09:55:46,141 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2020-01-16 09:55:46,142 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2020-01-16 09:55:46,143 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: <ClientID>
2020-01-16 09:55:46,143 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2020-01-16 09:55:46,144 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
>>> myAWSIoTMQTTClient.configureEndpoint("<awsBrokerURL>", 8883)
2020-01-16 09:55:46,150 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
>>> myAWSIoTMQTTClient.configureCredentials("/storage/certificates/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem", "/storage/certificates/<ClientID>/<shortID>-private.pem.key", "/storage/certificates/<ClientID>/<shortID>-certificate.pem.crt")
2020-01-16 09:55:46,181 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
>>> 
>>> 
>>> myAWSIoTMQTTClient.configureOfflinePublishQueueing(0)
2020-01-16 09:55:46,186 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
>>> myAWSIoTMQTTClient.configureDrainingFrequency(2)
2020-01-16 09:55:46,191 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
>>> myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)
2020-01-16 09:55:46,195 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
>>> myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)
2020-01-16 09:55:46,199 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
>>> myAWSIoTMQTTClient.connect()
2020-01-16 09:55:48,348 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2020-01-16 09:55:48,349 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2020-01-16 09:55:48,349 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2020-01-16 09:55:48,352 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2020-01-16 09:55:48,352 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2020-01-16 09:55:48,354 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2020-01-16 09:55:50,729 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Starting network I/O thread...
2020-01-16 09:55:50,876 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
2020-01-16 09:55:50,877 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
2020-01-16 09:55:50,880 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - No need for recovery
2020-01-16 09:55:50,881 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
True
>>> def print_errors(client, userdata, message):
...     serverError = json.loads(message.payload)
...     print serverError
... 
>>> 
>>> myAWSIoTMQTTClient.subscribe('stage/<ClientID>/<authToken>/measures/error', 1, print_errors)
2020-01-16 09:56:03,477 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2020-01-16 09:56:03,478 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Adding a new subscription record: stage/<ClientID>/<authToken>/measures/error qos: 1
2020-01-16 09:56:03,480 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom suback event callback...
2020-01-16 09:56:04,445 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [suback] event
2020-01-16 09:56:04,447 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [suback] event
2020-01-16 09:56:04,449 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2020-01-16 09:56:04,451 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - This custom event callback is for pub/sub/unsub, removing it after invocation...
True
>>> 2020-01-16 09:56:10,880 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - stableConnection: Resetting the backoff time to: 1 sec.

>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
2020-01-16 09:56:12,076 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2020-01-16 09:56:12,079 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom puback (QoS>0) event callback...
2020-01-16 09:56:13,032 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [puback] event
2020-01-16 09:56:13,033 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [puback] event
2020-01-16 09:56:13,034 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2020-01-16 09:56:13,034 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - This custom event callback is for pub/sub/unsub, removing it after invocation...
True
>>> 2020-01-16 09:56:13,481 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [message] event
2020-01-16 09:56:13,483 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [message] event
{u'isCustom': True, u'errors': [{u'field': u'payload.data', u'message': u'"data" is required', u'code': u'required'}], u'code': 400, u'type': u'Payload', u'name': u'ValidateError'}
2020-01-16 09:56:13,486 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...

>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
2020-01-16 09:56:25,180 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2020-01-16 09:56:25,183 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom puback (QoS>0) event callback...
2020-01-16 09:56:26,173 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [puback] event
2020-01-16 09:56:26,176 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [puback] event
2020-01-16 09:56:26,177 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2020-01-16 09:56:26,178 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - This custom event callback is for pub/sub/unsub, removing it after invocation...
True
>>> 2020-01-16 09:56:26,522 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [message] event
2020-01-16 09:56:26,524 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [message] event
{u'isCustom': True, u'errors': [{u'field': u'payload.data', u'message': u'"data" is required', u'code': u'required'}], u'code': 400, u'type': u'Payload', u'name': u'ValidateError'}
2020-01-16 09:56:26,527 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...

>>> 
>>> 
>>> os.system("ping google.com")
PING google.com (216.58.210.46): 56 data bytes
64 bytes from 216.58.210.46: seq=0 ttl=52 time=343.661 ms
64 bytes from 216.58.210.46: seq=1 ttl=52 time=329.042 ms
64 bytes from 216.58.210.46: seq=2 ttl=52 time=327.739 ms
64 bytes from 216.58.210.46: seq=3 ttl=52 time=338.289 ms
64 bytes from 216.58.210.46: seq=4 ttl=52 time=344.709 ms
64 bytes from 216.58.210.46: seq=5 ttl=52 time=339.847 ms
^C
--- google.com ping statistics ---
7 packets transmitted, 6 packets received, 14% packet loss
round-trip min/avg/max = 327.739/337.214/344.709 ms
2
>>> 
>>> 
>>> 
>>> os.system("ping google.com")
ping: bad address 'google.com'
256
>>> 
>>> 
>>> 
>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
2020-01-16 09:58:41,384 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2020-01-16 09:58:41,387 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom puback (QoS>0) event callback...
2020-01-16 09:58:46,389 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Removing custom event callback...
2020-01-16 09:58:46,391 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Publish timed out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 596, in publish
    return self._mqtt_core.publish(topic, payload, QoS, False)  # Disable retain for publish by now
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 248, in publish
    raise publishTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.publishTimeoutException
>>> 
>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
2020-01-16 09:58:51,456 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2020-01-16 09:58:51,458 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom puback (QoS>0) event callback...
2020-01-16 09:58:56,461 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Removing custom event callback...
2020-01-16 09:58:56,462 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Publish timed out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 596, in publish
    return self._mqtt_core.publish(topic, payload, QoS, False)  # Disable retain for publish by now
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 248, in publish
    raise publishTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.publishTimeoutException
>>> 
>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
2020-01-16 09:59:00,471 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2020-01-16 09:59:00,474 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in custom puback (QoS>0) event callback...
2020-01-16 09:59:05,475 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Removing custom event callback...
2020-01-16 09:59:05,476 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Publish timed out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 596, in publish
    return self._mqtt_core.publish(topic, payload, QoS, False)  # Disable retain for publish by now
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 248, in publish
    raise publishTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.publishTimeoutException
>>> 
```

**Comment by MickaelDelanoe** [comment]
As you can see in the previous comment, firstable I activate the internet connexion to build `myAWSIoTMQTTClient` object and connect to our AWS broker. After well connection and messages published, I disable internet connection of the IoT (to simulate an offline network).

I made an other test, with no network connexion at all (even to build client and connecion).
And, in this case, I got an `subscribeQueueDisabledException` at the publishing ...

```python
Python 2.7.11 (default, Feb  6 2019, 19:32:43) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import AWSIoTPythonSDK.MQTTLib as AWSIoTPyMQTT
>>> from AWSIoTPythonSDK.exception.AWSIoTExceptions import publishQueueDisabledException
>>> import sys, os, json
>>> import logging
>>> 
>>> logger = logging.getLogger("AWSIoTPythonSDK.core")
>>> logger.setLevel(logging.DEBUG)
>>> streamHandler = logging.StreamHandler()
>>> formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
>>> streamHandler.setFormatter(formatter)
>>> logger.addHandler(streamHandler)
>>> 
>>> myAWSIoTMQTTClient = AWSIoTPyMQTT.AWSIoTMQTTClient("<ClientID>")
2020-01-16 10:15:30,742 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2020-01-16 10:15:30,745 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2020-01-16 10:15:30,746 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2020-01-16 10:15:30,747 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: <ClientID>
2020-01-16 10:15:30,747 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2020-01-16 10:15:30,748 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
>>> myAWSIoTMQTTClient.configureEndpoint("<awsBrokerURL>", 8883)
2020-01-16 10:15:30,772 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
>>> myAWSIoTMQTTClient.configureCredentials("/storage/certificates/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem", "/storage/certificates/<ClientID>/<shortID>-private.pem.key", "/storage/certificates/<ClientID>/<shortID>-certificate.pem.crt")
2020-01-16 10:15:31,696 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
>>> 
>>> myAWSIoTMQTTClient.configureOfflinePublishQueueing(0)
2020-01-16 10:17:22,821 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: 0
>>> myAWSIoTMQTTClient.configureDrainingFrequency(2)
2020-01-16 10:17:22,825 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
>>> myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)
2020-01-16 10:17:22,828 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
>>> myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)
2020-01-16 10:17:22,844 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
>>> myAWSIoTMQTTClient.connect()
2020-01-16 10:17:23,306 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2020-01-16 10:17:23,307 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2020-01-16 10:17:23,308 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2020-01-16 10:17:23,311 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2020-01-16 10:17:23,312 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2020-01-16 10:17:23,314 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution
>>> 
>>> def print_errors(client, userdata, message):
...     serverError = json.loads(message.payload)
...     print serverError
... 
>>> 
>>> myAWSIoTMQTTClient.subscribe('stage/<ClientID>/<authToken>/measures/error', 1, print_errors)
2020-01-16 10:17:37,274 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2020-01-16 10:17:37,275 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2020-01-16 10:17:37,276 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Queue is disabled. Drop the message: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x765b0470>
2020-01-16 10:17:37,278 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 664, in subscribe
    return self._mqtt_core.subscribe(topic, QoS, callback)
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 274, in subscribe
    self._handle_offline_request(RequestTypes.SUBSCRIBE, (topic, qos, message_callback))
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 345, in _handle_offline_request
    raise self._offline_request_queue_disabled_exceptions[type]
AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeQueueDisabledException
>>> 
>>> myAWSIoTMQTTClient.publish('stage/<ClientID>/<authToken>/measures', '{"test": "MD"}', 1)
2020-01-16 10:17:48,217 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2020-01-16 10:17:48,219 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2020-01-16 10:17:48,220 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Queue is disabled. Drop the message: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x76be44f0>
2020-01-16 10:17:48,221 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 596, in publish
    return self._mqtt_core.publish(topic, payload, QoS, False)  # Disable retain for publish by now
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 240, in publish
    self._handle_offline_request(RequestTypes.PUBLISH, (topic, payload, qos, retain))
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 345, in _handle_offline_request
    raise self._offline_request_queue_disabled_exceptions[type]
AWSIoTPythonSDK.exception.AWSIoTExceptions.publishQueueDisabledException
>>> 
```

**Comment by MickaelDelanoe** [comment]
Hi @KaibaLopez ,
May I know why did you removed the "response-requested" label ?

**Comment by samvandamme** [comment]
Has this ever been resolved?

**Comment by MickaelDelanoe** [comment]
Thanks for asking, but no, it's not resolved

**Comment by MickaelDelanoe** [comment]
To bypass the problem i try to remove line who add message in a queue, who get the next one, cut the dispatching offline loop or something like that in the library. I tried many things without result, so if you have a bypass solution i will glad to have it :)

**Comment by MickaelDelanoe** [comment]
__As bypass solution__, I tried to modify draining frequency with `myAWSIoTMQTTClient.configureDrainingFrequency(0.2)`
This one seems to be have no effect neither.

__As other solution__, I tried to modify `_draining_interval_sec` sleep
https://github.com/aws/aws-iot-device-sdk-python/blob/0fb8d7859016386c0aa5dbd8e8aa07da8f187505/AWSIoTPythonSDK/core/protocol/internal/workers.py#L207 
of `_handle_draining` method by `time.sleep(5)`
And this had no effect, it is natural ?


__After all__, the only way I found, to reduce draining frequency, is to add a sleep() in `_dispatch` loop method (not so useful)
https://github.com/aws/aws-iot-device-sdk-python/blob/0fb8d7859016386c0aa5dbd8e8aa07da8f187505/AWSIoTPythonSDK/core/protocol/internal/workers.py#L146

Like this
```python
while not self._event_queue.empty():
    self._dispatch_one()
    time.sleep(5)
```

**Comment by MickaelDelanoe** [comment]
Otherwise, I logged qsize of `_event_queue` and it is equal to 0 or 1 with an offline of 10 messages.

https://github.com/aws/aws-iot-device-sdk-python/blob/0fb8d7859016386c0aa5dbd8e8aa07da8f187505/AWSIoTPythonSDK/core/protocol/internal/workers.py#L146
```py
while not self._event_queue.empty():
    self._dispatch_one()
    time.sleep(5)
    self._logger.debug("......._dispatch()...........Queue Size...... qsize=%s", self._event_queue.qsize())
```

I expected qsize=10, may be I wrong understand the code ?

**Comment by MickaelDelanoe** [comment]
After all, I think I have found a solution.
MQTT messages are store in `self._out_messages` from `paho.Client` 
https://github.com/aws/aws-iot-device-sdk-python/blob/0a2e9d38806a89f43cb093abac8fcb16b78e3cf5/AWSIoTPythonSDK/core/protocol/paho/client.py#L985

We can therefore manually manage this queue, from `MqttCore` Class (for example) by a path like :  `_mqtt_core._internal_async_client._paho_client._out_messages` according publish status returned by `mqtt_core.publish()`
https://github.com/aws/aws-iot-device-sdk-python/blob/0a2e9d38806a89f43cb093abac8fcb16b78e3cf5/AWSIoTPythonSDK/core/protocol/mqtt_core.py#L261

For my use case, when publish status is False, I clear the queue by : 
```python
if status is False:
    outMessagesList = [personalPath]._mqtt_core._internal_async_client._paho_client._out_messages
    outMessagesLen = len(outMessagesList)
    if outMessagesLen > 1:
        outMessagesList[:] = []
```

Hoping it can help someone else :)

**Comment by jmklix** [comment]
I'm going to change this to a bug. I can confirm that setting configureOfflinePublishQueueing(0) doesn't seem to work no matter what the configurations are.
