### ISSUE TITLE
_tokenPool KeyError in deviceShadow

### ISSUE THREAD

**Issue by 780Farva** [aws/aws-iot-device-sdk-python#257]
Using `AWSIoTPythonSDK==1.4.3`, I've caught a `KeyError` exception inside `core.shadow.deviceShadow`

```
 2020-06-10 16:27:50,104 [INFO] AWSIoTPythonSDK.core.protocol.mqtt_core: Performing sync publish...
 Exception in thread Thread-3:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.7/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2913, in _thread_main
     self.loop_forever(retry_first_connection=True)
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
     rc = self.loop(timeout, max_packets)
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1072, in loop
     rc = self.loop_read(max_packets)
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
     rc = self._packet_read()
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
     rc = self._packet_handle()
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
     return self._handle_publish()
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
     self._handle_on_message(message)
   File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
     callback(self, self._userdata, message)
   File "/opt/awsiot-bridge/src/awsiot-bridge.py", line 492, in on_modbus_complete
     device_shadow_handler.shadowUpdate(connected=True)
   File "/opt/awsiot-bridge/src/shadowmanger.py", line 76, in shadowUpdate
     self.client.shadowUpdate(payload_template, self._update, timeout)
   File "/usr/local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/shadow/deviceShadow.py", line 362, in shadowUpdate
     self._tokenPool[currentToken].start()
 KeyError: '71c853b3-4ee3-49ac-a936-cd62e3e5406e'
```

After reviewing `AWSIoTPythonSDK/core/shadow/deviceShadow.py` I'm pretty confused as to how the `currentToken` that was just added to that dictionary could be missing. Seems like there might be a race-condition or some side-effect internal to the library causing this one. 

A second set of eyes would be greatly appreciaed!

**UPDATE**: This issue was just observed again on 2020-06-23

**Comment by 780Farva** [comment]
@bretambrose @TingDaoK I hate to be that guy that pings on GitHub, but have you had a chance to have a look at the above?

**Comment by bretambrose** [comment]
It's hard to get much from a call stack.  Are you able to supply logs from when it happened and/or sample code/repro steps?

**Comment by 780Farva** [comment]
Thanks for getting back! I'll put together some content and context that I can capture and share. I appreciate the help.

**Comment by 780Farva** [comment]
Ok, here's a stack trace from the time a message was handed off to the sdk to when the error gets thrown. Thanks for having a look!

```
2020-07-10 21:38:49,458 [INFO] AWSIoTPythonSDK.core.protocol.mqtt_core: Performing sync publish...
2020-07-10 21:38:49,459 [DEBUG] AWSIoTPythonSDK.core.protocol.internal.workers: Produced [puback] event
2020-07-10 21:38:49,459 [DEBUG] AWSIoTPythonSDK.core.protocol.internal.workers: Dispatching [puback] event
2020-07-10 21:38:49,497 [DEBUG] AWSIoTPythonSDK.core.protocol.internal.workers: Produced [message] event
2020-07-10 21:38:49,498 [DEBUG] AWSIoTPythonSDK.core.protocol.internal.workers: Dispatching [message] event
2020-07-10 21:38:49,498 [DEBUG] AWSIoTPythonSDK.core.shadow.deviceShadow: shadow message clientToken: b639815b-f5d5-42ce-94ad-f748df2f950e
2020-07-10 21:38:49,498 [DEBUG] AWSIoTPythonSDK.core.shadow.deviceShadow: Token is in the pool. Type: accepted
2020-07-10 21:38:49,517 [DEBUG] AWSIoTPythonSDK.core.protocol.internal.clients: Invoking custom event callback...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2913, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "/opt/awsiot-bridge/src/awsiot-bridge.py", line 504, in on_modbus_complete
    device_shadow_handler.shadowUpdate(connected=True)
  File "/opt/awsiot-bridge/src/shadowmanger.py", line 71, in shadowUpdate
    self.client.shadowUpdate(payload_template, self._update, timeout)
  File "/usr/local/lib/python3.7/site-packages/AWSIoTPythonSDK/core/shadow/deviceShadow.py", line 362, in shadowUpdate
    self._tokenPool[currentToken].start()
KeyError: 'b639815b-f5d5-42ce-94ad-f748df2f950e'
```

**Comment by rccarper** [comment]
Hello!  I'm also suspecting a possible race condition in the library.  It looks like generalCallback used in shadowUpdate can remove the token from the dictionary.  I'm wondering if it can get called quickly enough that the token is removed before shadowUpdate can use it where the crash happens.  (Still just a theory though!)  How often are you hitting the crash?  Are you seeing this in your own project or one of the samples?

**Comment by 780Farva** [comment]
Hi @rccarper. I'm glad we came to the same conclusion about `generalCallback`. Its odd though, the `.start()` call for a thread affected by `generalCallback` is after the subscription to it, so I'm a bit perplexed about how that potential race condition could actually get hit. Probably worth another read-through.

This is not from the samples, unfortunately. We hit the crash a handful of times a week. We haven't been able to find any discernable pattern to it, and it pops up across multiple deployments. One little clue is that it happens more frequently if one of our devices experiences some resource constraints (memory pressure, disk exhaustion etc).

**Comment by rccarper** [comment]
Because the subscribe is asynchronous, it could be possible for it to finish from another thread, removing the timer in the dictionary before start has a chance to be called.  It's possible that the resource constraints are affecting the performance in the script, making the race condition more likely.  (That's slightly speculative on my part though.)  I'll try to get a fix in by early next week.

**Comment by rccarper** [comment]
Sorry for the delay on the fix, I'm working through a possible issue with it.  We'll respond back soon once we have another update!

**Comment by rccarper** [comment]
I'm working on getting the fix through our release process.  Once that happens, it'll be available here.

**Comment by rccarper** [comment]
The fix is now in this Github repo, as well as in PyPI under version 1.4.9.  I'll close out this ticket, but if you see the issue again, just let us know!

**Comment by 780Farva** [comment]
Awesome, I'll pull that version and get using it. Thanks a bunch!
