### ISSUE TITLE
Greengrass sample can't connect to Greengrass running on another machine

### ISSUE THREAD

**Issue by mstfldmr** [aws/aws-iot-device-sdk-python#258]
If Greengrass is running on another machine, sample code at samples/greengrass/basicDiscovery.py tries to connect to localhost (instead of the machine running GG) and fails.

```
python3 basicDiscovery.py -e ENDPOINT -r root.ca.pem -c 7e7b649e5e.cert.pem -k 7e7b649e5e.private.key -n MyDevice -t test -M abc123

2020-07-01 01:01:17,451 - AWSIoTPythonSDK.core.greengrass.discovery.providers - INFO - Starting discover request...
2020-07-01 01:01:17,451 - AWSIoTPythonSDK.core.greengrass.discovery.providers - INFO - Endpoint: ENDPOINT:8443
2020-07-01 01:01:17,451 - AWSIoTPythonSDK.core.greengrass.discovery.providers - INFO - Target thing: MyDevice
2020-07-01 01:01:17,451 - AWSIoTPythonSDK.core.greengrass.discovery.providers - DEBUG - Creating tcp connection...
2020-07-01 01:01:17,494 - AWSIoTPythonSDK.core.greengrass.discovery.providers - DEBUG - Creating ssl connection...
2020-07-01 01:01:17,562 - AWSIoTPythonSDK.core.greengrass.discovery.providers - DEBUG - Matching host name...
2020-07-01 01:01:17,562 - AWSIoTPythonSDK.core.greengrass.discovery.providers - DEBUG - Sending discover request: GET /greengrass/discover/thing/MyDevice HTTP/1.1
Host: ENDPOINT:8443


2020-07-01 01:01:17,562 - AWSIoTPythonSDK.core.greengrass.discovery.providers - DEBUG - Receiving discover response header...
2020-07-01 01:01:18,009 - AWSIoTPythonSDK.core.greengrass.discovery.providers - DEBUG - Receiving discover response body...
Discovered GGC: arn:aws:iot:eu-west-1:591128969213:thing/PredictiveMaintenance_Core from Group: f6c18be1-296c-44a1-9569-349e30c9dc7c
Now we persist the connectivity/identity information...
Now proceed to the connecting flow...
2020-07-01 01:01:18,015 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2020-07-01 01:01:18,016 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2020-07-01 01:01:18,016 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2020-07-01 01:01:18,016 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: MyDevice
2020-07-01 01:01:18,016 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2020-07-01 01:01:18,016 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2020-07-01 01:01:18,016 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
Trying to connect to core at 127.0.0.1:8883
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2020-07-01 01:01:18,017 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2020-07-01 01:01:18,018 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Waiting for event consumer to completely stop
2020-07-01 01:01:18,028 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Exiting dispatching loop...
2020-07-01 01:01:18,028 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Event consumer stopped
Error in connect!
Type: <class 'ConnectionRefusedError'>
Traceback (most recent call last):
  File "basicDiscovery.py", line 157, in <module>
    myAWSIoTMQTTClient.connect()
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 223, in connect_async
    raise e
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 211, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 122, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 665, in connect
    return self.reconnect()
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 789, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Users/aldemim/opt/miniconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basicDiscovery.py", line 163, in <module>
    print("Error message: %s" % e.message)
AttributeError: 'ConnectionRefusedError' object has no attribute 'message'
```

If localhost is skipped, it works:

```
if currentHost == '127.0.0.1':
        continue
```

**Comment by TingDaoK** [comment]
It looks like the connection gets refused by the local server. Probably because of the security problem while you are trying to connect from another machine. 
We strongly recommend you to try our [v2 sdk](https://github.com/aws/aws-iot-device-sdk-python-v2) instead, which is built to improve reliability, performance, and security!

**Comment by kevasync** [comment]
Another work around is to change line 160 from ` print("Error message: %s" % e.message)` to  `print("Error message: %s" % e)`

If you look at that last error message, it is blowing up in the catch block because it cannot get at the property `message` on the exception
