### ISSUE TITLE
Problem connecting AWS IoT

### ISSUE THREAD

**Issue by navalkishoreb** [aws/aws-iot-device-sdk-python#26]
Traceback (most recent call last):
    File "./publisher.py", line 85, in <module>
    client.connect(config.HOST,config.PORT)
    File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
    File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 821, in reconnect
    ciphers=self._tls_ciphers)
    File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
    File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
    File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()

    ssl.SSLError: [Errno 1] _ssl.c:504: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

Hey, I am using _paho.mqtt_ library  to connect, which is also core for this wrapper. 
But, I am not able to get past above mentioned error.
I thought the problem is with TLS version. 
Python 2.7 has _ssl.PROTOCOL_TLSv1 = 3_  max version.

However, [you are using ssl.PROTOCOL_SSLv23](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqttCore.py#L284)  and it supposed to work fine.

Here, are the details I supplied
_client id: gateway
ca_certs: '/root/aws_iot/keys/ca.pem.cert'
certfile: '/root/aws_iot/keys/aws.pem.cert'
keyfile: '/root/aws_iot/keys/private.pem.key'
host: ***********.iot.*******.amazonaws.com
port: 8883_

Could you help me??

**Comment by liuszeng** [comment]
Hi @navalkishoreb ,

Thank you very much for your interest in AWS IoT Python SDK!

AWS IoT supports several types of identity principals for authentication. More details can be found here:
http://docs.aws.amazon.com/iot/latest/developerguide/identity-in-iot.html

For the X.509 certificate based mutual authentication, it requires TLSv1.2+ and certain set of cypher suite to complete the SSL handshake. See documentation here:
http://docs.aws.amazon.com/iot/latest/developerguide/x509-certs.html

There are several things you can do here:
a. Verify the SSL version compiled with your Python executable.
Use the following commands:

    >>> import ssl
    >>> ssl.OPENSSL_VERSION

It should give you openssl version 1.0.1+ in order to have the SDK/Paho working correctly.

b. Verify that you are configuring the right TLS version to use in SDK/Paho.
The SDK does the following configuration to the Paho client underneath it:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqttCore.py#L284

Note that TLS support in Python only starts from v2.7 and we cannot force it to use the TLSv1.2 in Python 2.7. `PROTOCL_SSLv23` here will select the highest TLS version between the client and the server. If openssl v1.0.1+ is installed and compiled with the Python executable, the correct TLS version will get picked up.

Which Python version are you using? Can you verify the openssl version and also check `tls_set` in your code base and see if they are correctly configured?

Thanks,
Liusu

**Comment by navalkishoreb** [comment]
Thank you for your quick reply.

I am using **Python 2.7**

ssl.OPENSSL_VERSION
**'OpenSSL 1.0.1t  3 May 2016'** 

Here is how  I am setting tls.
```
client.tls_set(ca_certs = config.CA_PATH,
                certfile = config.CERT,
                keyfile = config.KEY,
                cert_reqs = ssl.CERT_REQUIRED,
                tls_version = ssl.PROTOCOL_TLSv1)
```


Can I see server logs?? Or can I know the reason why server might be rejecting??

**Comment by liuszeng** [comment]
Hi @navalkishoreb ,

Thank you very much for providing the information.

As mentioned in the previous post for the X.509 certificate based mutual authentication, AWS IoT requires TLSv1.2+ and certain set of cypher suite to complete the SSL handshake. Since Python 2.7 does not have the TLS configuration above TLS v1.0: `ssl.PROTOCOL_TLSv1`, you will need to configure it to pick up the highest TLS supported for both the client and server sides:

    client.tls_set(
        ca_certs=config.CA_PATH, 
        cerfile=config.CERT, 
        keyfile=config.KEY, 
        cert_reqs=ssl.CERT_REQUIRED, 
        tls_version=ssl.PROTOCOL_SSLv23)

For detailed information about `ssl.PROTOCOL_SSLv23`, please check out the following link:
https://docs.python.org/2/library/ssl.html#socket-creation

As for server log, you can set up the CloudWatchLog. More information can be found here:
http://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html

Can you try the above TLS configuration and see if it gets connected?

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @navalkishoreb ,

We haven't heard from you for a while. Are you still having issue using the SDK? We will close the issue for now. Please feel free to reopen it or start a new thread if you have more questions.

Thanks,
Liusu

**Comment by kejsiStruga** [comment]
Hello @liuszeng ,

I am facing the same problem, when trying to connect to AWS IoT via python. My code worked previously so there isn't anything I can change there, I suspect there is something on AWS side probably ? As you can see at the last line I am having SSL problems. 
`Traceback (most recent call last):
  File "flint.py", line 44, in <module>
    mqttc.connect("a2yye602yte99c.iot.us-west-2.amazonaws.com", port=8883) #AWS IoT service hostname and portno
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 821, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:581)`

Also yesterday when error popped in for the first time, there was some notification on AWS IoT console :+1: 
![notify](https://cloud.githubusercontent.com/assets/20498500/22139443/394cb2ec-dee6-11e6-8c0c-d33e8d0c5ee8.PNG)

**Comment by kejsiStruga** [comment]
Hey, @navalkishoreb did you solve this issue ? Im not able to understand the root cause of it.

**Comment by mvtango** [comment]
I had the same problem (python 3.5.2, paho-mqtt 1.2, linux 64bit). I solved it by using this undocumented flag in the client:

> client._tls_ca_certs=None

It means that the client cannot check if the servers' certificate is legit, because it does not know of any certificate authorities. This means there is a way for a malicious attacker to impersonate the server, and I won't notice. I can live with that for now, certainly not for a productionenvironment.

I found no way of a) getting the server certificate from the AWS IoT broker, much less make it knonw to my client. It would be good to have a tutorial for this.

**Comment by gbassan-br** [comment]
I had the same problem with "SSLV3_ALERT_CERTIFICATE_UNKNOWN" because the certificate was not active on AWS IoT console, just thing attached to it. Once I activated it paho is working just fine

**Comment by bandinigo** [comment]
Same problem as @gbassan-br. However I could not find an option to activate an AWS IoT device once it is created. And also on the AWS IoT console one cannot see if a device is activated or not. 
Or did I just not find it? And it is possible to active a device once it is created?

**Comment by soundarsurya** [comment]
when i run ./start.sh from the IoT certificates, it shows like this.....

Running pub/sub sample application...
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: basicPubSub
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 99, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_verify_locations(ca_certs)
ssl.SSLError: unknown error (_ssl.c:2831)

how could i fix this..????

**Comment by ubipalle** [comment]
I had the exact same problem. Turned out that my root-CA.crt file was empty. I deleted it, and ran start.sh again, and then it worked

**Comment by soundarsurya** [comment]
Wow that's great.
I'll try and tell you....

**Comment by gaaschk** [comment]
> I had the exact same problem. Turned out that my root-CA.crt file was empty. I deleted it, and ran start.sh again, and then it worked

This worked for me also! I didn't even think to look at the root_CA.crt file!

**Comment by carollion105** [comment]
When I run the device shadow report information, the following situation occurs:
