### ISSUE TITLE
Invalid Certificate - i think rootCA

### ISSUE THREAD

**Issue by Bobsilvio** [aws/aws-iot-device-sdk-python#268]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727): SSLError
Traceback (most recent call last):
  File "/var/task/mqtt-handler.py", line 68, in lambda_handler
    return handleDiscovery(request)
  File "/var/task/mqtt-handler.py", line 131, in handleDiscovery
    publish('log', 
{
    "discovery": "Responding to Discovery Request"
}
)
  File "/var/task/mqtt-handler.py", line 90, in publish
    client.connect()
  File "/var/task/AWSIoTPythonSDK/MQTTLib.py", line 405, in connect
    return self._mqttCore.connect(keepAliveIntervalSecond)
  File "/var/task/AWSIoTPythonSDK/core/protocol/mqttCore.py", line 290, in connect
    self._pahoClient.connect(self._host, self._port, keepAliveInterval)  # Throw exception...
  File "/var/task/AWSIoTPythonSDK/core/protocol/paho/client.py", line 655, in connect
    return self.reconnect()
  File "/var/task/AWSIoTPythonSDK/core/protocol/paho/client.py", line 798, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by bretambrose** [comment]
More context would be useful; an exception stack doesn't tell us much in isolation.

Are you using the *-ats endpoint (<prefix>-ats.iot.<region>.amazonaws.com)?  Are you using the correct root ca? (https://www.amazontrust.com/repository/AmazonRootCA1.pem)

**Comment by Bobsilvio** [comment]
Ok thanks with this CA, work server. 
Now i have a problem with client.
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
if port is 8883...
if set 8884 nothing error display(but not work)

    client = AWSIoTMQTTClient(clientId)
    client.configureEndpoint(host, 8883)
    client.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

    client.configureAutoReconnectBackoffTime(1, 32, 20)
    client.configureOfflinePublishQueueing(-1)
    client.configureDrainingFrequency(2)
    client.configureConnectDisconnectTimeout(10)
    client.configureMQTTOperationTimeout(5)

    client.connect()

**Comment by bretambrose** [comment]
I'm not sure what you mean by server vs. client.  This SDK is only really appropriate for clients connecting to the Aws IoT broker.

Are you able to connect using a downloaded connection kit?

**Comment by Bobsilvio** [comment]
No.
Tested with basicpubsub

> python testclient.py -e XXXXXXX-ats.iot.eu-west-1.amazonaws.com -r root-CA.crt -c Device.cert.pem -k Device.private.key -id Device -t things/lambda/V3
2020-09-19 10:11:46,170 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Paho MQTT Client init.
2020-09-19 10:11:46,171 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - ClientID: Device
2020-09-19 10:11:46,171 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Protocol: MQTTv3.1.1
2020-09-19 10:11:46,171 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Register Paho MQTT Client callbacks.
2020-09-19 10:11:46,171 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - mqttCore init.
2020-09-19 10:11:46,172 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load CAFile from: root-CA.crt
2020-09-19 10:11:46,172 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Key from: Device.private.key
2020-09-19 10:11:46,172 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Cert from: Device.cert.pem
2020-09-19 10:11:46,172 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: baseReconnectTime = 1 sec
2020-09-19 10:11:46,173 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: maximumReconnectTime = 32 sec
2020-09-19 10:11:46,173 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: minimumConnectTime = 20 sec
2020-09-19 10:11:46,173 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: queueSize = -1
2020-09-19 10:11:46,173 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: dropBehavior = Drop Newest
2020-09-19 10:11:46,174 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for draining interval: 0.5 sec
2020-09-19 10:11:46,174 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum connect/disconnect timeout to be 10 second.
2020-09-19 10:11:46,174 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum MQTT operation timeout to be 5 second
2020-09-19 10:11:46,174 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connection type: TLSv1.2 Mutual Authentication
2020-09-19 10:11:46,601 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Disconnect result code 1
2020-09-19 10:11:46,602 - AWSIoTPythonSDK.core.util.progressiveBackoffCore - DEBUG - backOff: current backoff time is: 1 sec.
2020-09-19 10:11:47,965 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Disconnect result code 1
2020-09-19 10:11:47,965 - AWSIoTPythonSDK.core.util.progressiveBackoffCore - DEBUG - backOff: current backoff time is: 2 sec.
2020-09-19 10:11:50,306 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Disconnect result code 1
2020-09-19 10:11:50,307 - AWSIoTPythonSDK.core.util.progressiveBackoffCore - DEBUG - backOff: current backoff time is: 4 sec.
2020-09-19 10:11:54,664 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Disconnect result code 1
2020-09-19 10:11:54,665 - AWSIoTPythonSDK.core.util.progressiveBackoffCore - DEBUG - backOff: current backoff time is: 8 sec.
2020-09-19 10:11:56,574 - AWSIoTPythonSDK.core.protocol.mqttCore - ERROR - Connect timeout.
Traceback (most recent call last):
  File "testclient.py", line 108, in <module>
    myAWSIoTMQTTClient.connect()
  File "/var/volatile/tmp/client/AWSIoTPythonSDK/MQTTLib.py", line 405, in connect
    return self._mqttCore.connect(keepAliveIntervalSecond)
  File "/var/volatile/tmp/client/AWSIoTPythonSDK/core/protocol/mqttCore.py", line 299, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException

**Comment by Bobsilvio** [comment]
Ok is my bad config...if is:
topic= "sdk/test/Python"
clientId = "basicPubSub"
all work..
is possible personalize this?

**Comment by bretambrose** [comment]
Certainly, but if the associated permissions policy checks any of those values you'll need to relax it.

**Comment by jmklix** [comment]
@Bobsilvio have you had any success? Have you tried relaxing the policy permissions?

**Comment by Bobsilvio** [comment]
yes, I recreated the certificates with the policies. Everything good.
