### ISSUE TITLE
MQTT Connection time out exception when using Cognito Credentials.

### ISSUE THREAD

**Issue by cepldev** [aws/aws-iot-device-sdk-python#278]
I tried to connect to the AWS IoT MQTT with credentials fetched through a cognito identity and the following exception is received.

```
Connect timed out
Traceback (most recent call last):
  File "C:\Users\Software\Desktop\cognito test code .py", line 114, in <module>
    myAWSIoTMQTTClient.connect()
  File "C:\Users\Software\AppData\Local\Programs\Python\Python36\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "C:\Users\Software\AppData\Local\Programs\Python\Python36\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 199, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException
```

Also I am Attaching the test code below

```
import datetime as dt
import boto3
import botocore.exceptions
import hmac
import hashlib
import base64
import json
from boto3 import dynamodb
from boto3.session import Session
from boto3.dynamodb.conditions import Key,Attr
import os
import time
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient


USER_POOL_ID = 'xxxxxxxxxx'
CLIENT_ID = 'xxxxxxxxxx'
CLIENT_SECRET = 'xxxxxxxxxx'
IDENTITY_POOL_ID = 'xxxxxxxxxx'
PROVIDER = f'cognito-idp.xxxxxxxxxx.amazonaws.com/{USER_POOL_ID}'

os.environ['AWS_DEFAULT_REGION'] = 'ap-south-1'
rootCAPath = "root-CA.crt"

host = "xxxxxxxxxx-ats.iot.xxxxxxxxxx.amazonaws.com"

topic = 'device/xxxxxxxxxx/xxxxxxxxxx'



def customCallback(client, userdata, message):
    print("Received a new message: ")
    print(message.payload)
    print("from topic: ")
    print(message.topic)
    print("--------------\n\n")



def get_secret_hash(username):
    msg = username + CLIENT_ID
    dig = hmac.new(str(CLIENT_SECRET).encode('utf-8'),
    msg = str(msg).encode('utf-8'), digestmod=hashlib.sha256).digest()
    d2 = base64.b64encode(dig).decode()
    return d2

def initiate_auth(client, username, password):
    secret_hash = get_secret_hash(username)
    try:
        resp = client.admin_initiate_auth(
                    UserPoolId = USER_POOL_ID,
                    ClientId = CLIENT_ID,
                    AuthFlow = 'ADMIN_NO_SRP_AUTH',
                    AuthParameters = {
                        'USERNAME': username,
                        'SECRET_HASH': secret_hash,
                        'PASSWORD': password,
                    },
                    ClientMetadata = {
                        'username': username,
                        'password': password,
                    }
                )
    except client.exceptions.NotAuthorizedException:
        return None, "The username or password is incorrect"
    except client.exceptions.UserNotConfirmedException:
        return None, "User is not confirmed"
    except Exception as e:
        return None, e.__str__()
    return resp, None


client = boto3.client('cognito-idp',
                       aws_access_key_id="xxxxxxxxxx",
                       aws_secret_access_key="xxxxxxxxxx",
                       region_name="xxxxxxxxxx")

id_client = boto3.client('cognito-identity')

username = 'xxxxxxxxxx'
password = 'xxxxxxxxxx'

resp, msg = initiate_auth(client, username, password)

print(resp)

id_token = resp['AuthenticationResult']["IdToken"]
identity_response = id_client.get_id(IdentityPoolId=IDENTITY_POOL_ID, Logins={PROVIDER: id_token})
identity_id = identity_response['IdentityId']
response = id_client.get_credentials_for_identity(IdentityId=identity_id, Logins={PROVIDER: id_token})
res = response["Credentials"]

print(res)

clientId = 'test_user'

AccessKeyId = res["AccessKeyId"]
SecretKey = res["SecretKey"]
SessionToken = res["SessionToken"]


# Init AWSIoTMQTTClient
myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)

# AWSIoTMQTTClient configuration
myAWSIoTMQTTClient.configureEndpoint(host, 443)
myAWSIoTMQTTClient.configureCredentials(rootCAPath)
myAWSIoTMQTTClient.configureIAMCredentials(AccessKeyId, SecretKey, SessionToken)
myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myAWSIoTMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec

# Connect and subscribe to AWS IoT
myAWSIoTMQTTClient.connect()
myAWSIoTMQTTClient.subscribe(topic, 1, customCallback)
time.sleep(2)

loopCount = 0
while True:
    myAWSIoTMQTTClient.publish(topic, "New Message " + str(loopCount), 1)
    loopCount += 1
    time.sleep(1)
```

**Comment by cepldev** [comment]
I have checked policies ,but it seems fine

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by jmklix** [comment]
Where you able to connect using the basicPubSub_CognitoSTS.py sample that just uses a `CognitoIdentityPoolID`?
```python
python basicPubSub_CognitoSTS.py -e <endpoint> -r <rootCAFilePath> -C <CognitoIdentityPoolID>
```
