### ISSUE TITLE
Connection refused: Unable to run lightController.py file 

### ISSUE THREAD

**Issue by supriya-s-jadhav** [aws/aws-iot-device-sdk-python#285]
Devices details:
1)EC2 as AWS IOT Greengrass core
2) Mac laptop 
3) Trying to run TrafficLight example (Module 5 from here https://docs.aws.amazon.com/greengrass/v1/developerguide/comms-disabled.html)

I have created a folder "test" that has cert,public key, private key of gg_switch and gg_trafficlight,roo cert, lightcontroller.py and trafficlight.py. Ping command works fine. Now, when I am trying to run the below command:
cd path-to-certs-folder
python lightController.py --endpoint AWS_IOT_ENDPOINT --rootCA root-ca-cert.pem --cert switch.cert.pem --key switch.private.key --thingName GG_TrafficLight --clientId GG_Switch
I got errors as follows:
Traceback (most recent call last):
File "lightController.py", line 210, in
myAWSIoTMQTTShadowClient.connect()
File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 1271, in connect
return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 513, in connect
return self._mqtt_core.connect(keepAliveIntervalSecond)
File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect
self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
File "/Library/Python/2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 223, in connect_async
raise e
socket.error: [Errno 61] Connection refused

What did I miss in the configuration setting? I appreciate your response to my query. Thank you so much in advance for your time and help.

**Comment by jmklix** [comment]
What does the permissions policy look like for the certificate? It's a json file that you can find on the IoT console.
