### ISSUE TITLE
Cannot run basic pubsub via start.sh

### ISSUE THREAD

**Issue by tucker-SB** [aws/aws-iot-device-sdk-python#332]
### Describe the bug

Attempting to run the example code from the connection kit via start.sh does not work

### Expected Behavior

Starts continuously publishing

### Current Behavior

Gives the traceback

Running pub/sub sample application...
Traceback (most recent call last):
  File "/home/todd_keitel/Downloads/aws-iot-device-sdk-python-v2/samples/pubsub.py", line 84, in <module>
    mqtt_connection = mqtt_connection_builder.mtls_from_path(
  File "/home/todd_keitel/.local/lib/python3.10/site-packages/awsiot/mqtt_connection_builder.py", line 276, in mtls_from_path
    return _builder(tls_ctx_options, **kwargs)
  File "/home/todd_keitel/.local/lib/python3.10/site-packages/awsiot/mqtt_connection_builder.py", line 231, in _builder
    tls_ctx = awscrt.io.ClientTlsContext(tls_ctx_options)
  File "/home/todd_keitel/.local/lib/python3.10/site-packages/awscrt/io.py", line 596, in __init__
    self._binding = _awscrt.client_tls_ctx_new(
RuntimeError: 34 (AWS_ERROR_INVALID_ARGUMENT): An invalid argument was passed to a function.

### Reproduction Steps

Run the startup script

### Additional Information/Context

This tutorial worked fine on Mac, attempting to run on Ubuntu

### SDK version used

awsiotsdk - 1.21.0, awscrt - 0.20.2

### Environment details (OS name and version, etc.)

Ubuntu 22.04.3

**Comment by jmklix** [comment]
This is the wrong repo, the startup script installs the [v2 version](https://github.com/aws/aws-iot-device-sdk-python-v2) of this sdk. Can you make sure your arguments that the startup script is passing are correct because that is the error that you are getting `(AWS_ERROR_INVALID_ARGUMENT): An invalid argument was passed to a function.` If you still are having any problems please open a new issue on the v2 repo
