### ISSUE TITLE
Hangs on connect

### ISSUE THREAD

**Issue by richmondwatkins** [aws/aws-iot-device-sdk-python#34]
I can connect with the node.js sdk using the same certs and endpoint. However, with this SDK it hangs on `.connect()`. 

Code:
```from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTShadowClient

# For certificate based connection
myShadowClient = AWSIoTMQTTShadowClient("RWRaspberryPi")
# For Websocket connection
# myMQTTClient = AWSIoTMQTTClient("myClientID", useWebsocket=True)
# Configurations
# For TLS mutual authentication
myShadowClient.configureEndpoint("a3pzb0u64rd1gp.iot.us-east-1.amazonaws.com", 8883)
# For Websocket
# myShadowClient.configureEndpoint("YOUR.ENDPOINT", 443)
myShadowClient.configureCredentials("/Users/richmond.watkins/Documents/HomeSecurity/certs/root-ca.crt", "/Users/richmond.watkins/Documents/HomeSecurity/certs/9e95daa236-private.pem.key", "/Users/richmond.watkins/Documents/HomeSecurity/certs/9e95daa236-certificate.pem.crt")
# For Websocket, we only need to configure the root CA
# myShadowClient.configureCredentials("YOUR/ROOT/CA/PATH")
myShadowClient.configureConnectDisconnectTimeout(10)  # 10 sec
myShadowClient.configureMQTTOperationTimeout(5)  # 5 sec


myShadowClient.connect()
# Create a device shadow instance using persistent subscription
myDeviceShadow = myShadowClient.createShadowHandlerWithName("RWRaspberryPi", True)
# Shadow operations
myDeviceShadow.shadowGet(customCallback, 5)
myDeviceShadow.shadowUpdate(myJSONPayload, customCallback, 5)
myDeviceShadow.shadowDelete(customCallback, 5)
myDeviceShadow.shadowRegisterDeltaCallback(customCallback)
myDeviceShadow.shadowUnregisterDeltaCallback()

```

**Comment by liuszeng** [comment]
Hi @richmondwatkins ,

Thank you very much for using AWS IoT Python SDK.

Can you enable the SDK logging and see where it gets hanged? Also, can you try running the provided sample using the same credentials?
https://github.com/aws/aws-iot-device-sdk-python/tree/master/samples

Thanks,
Liusu

**Comment by richmondwatkins** [comment]
Thanks for the response @liuszeng. I've got it working now. For some reason it doesn't work on my home network but does work on my phone's hotspot. Do you have any idea why that would be the case?

**Comment by richmondwatkins** [comment]
The node sdk works on my home network but not this one for some reason.

**Comment by liuszeng** [comment]
Hi @richmondwatkins ,

One thing you can try is to test the reachability of the endpoint/SSL handshake on different network.

You can use the following steps for TCP connection verification:

From your <PC> machine try a simple telnet command to the service hostname and port

    host$> telnet <PREFIX>.iot.<REGION>.amazonaws.com 8883
    Trying 54.236.141.103...
    Connected to iotmoonraker-u-elb-<SOME_HASH>.<REGION>.elb.amazonaws.com.
    Escape character is '^]'.

    Connection closed by foreign host.
    host$> 

The above shows a successful TCP connection, with the connection eventually being closed due to failed authentication. This would indicate connections on port 8883 are not being blocked. Below shows the same command when attempting on a blocked port:

    host$> telnet <PREFIX>.iot.<REGION>.amazonaws.com 8883
    Trying 54.236.141.103...
    telnet: connect to address 54.236.141.103: Connection refused
    Try connecting using the SDK from a different network (e.g. a home network or guest network).

If TCP connection is good, you can use the following steps for SSL handshake verification:

Type the following command into the linux command line if you have OpenSSL installed

    openssl s_client -connect <customer endpoint>:8883 -tls1_2 -CAfile <path to Root CA cert> -cert <Path to device cert> -key <Path to device private key>

If the command fails you will get an output similar to below

    SSL routines:ssl3_write_bytes:ssl handshake failure

If it succeeds you will have a success message and the command will wait for further input.

Hope the above helps.

Thanks,
Liusu

**Comment by richmondwatkins** [comment]
It is getting hung up on the TCP connection. It eventually will time out and then try again. Any idea why the node.js SDK is able to connect when this one can't? I can run the node.js SDK on the same network with the same credentials and it works just fine.

**Comment by richmondwatkins** [comment]
I can also connect with the MQTT.fx app on the same network.

**Comment by richmondwatkins** [comment]
Turns out my router doesn't support IPv6 and paho mqtt tries to force it as IPv6. If anyone runs into something similar then you should try resolving the hostname to IPv4. 

Example (currently line 808 in the paho mqtt client.py file):

```
host = socket.gethostbyname(self._host)
sock = socket.create_connection((host, self._port), source_address=(self._bind_address, 0))
```

**Comment by soundarsurya** [comment]
i'm getting SSL certificate issue while running(see the last line)

Running pub/sub sample application...
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Initializing MQTT layer...
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Registering internal event callbacks to MQTT layer...
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - MqttCore initialized
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Client id: basicPubSub
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Protocol version: MQTTv3.1.1
2018-01-17 22:06:37,553 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Authentication type: TLSv1.2 certificate based Mutual Auth.
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring endpoint...
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring certificates...
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring reconnect back off timing...
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Base quiet time: 1.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Max quiet time: 32.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Stable connection time: 20.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 10.000000 sec
2018-01-17 22:06:37,554 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 600.000000 sec
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread started
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2018-01-17 22:06:37,555 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 99, in <module>
    myAWSIoTMQTTClient.connect()
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 481, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 183, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 196, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 116, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/soundar/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 797, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_verify_locations(ca_certs)
ssl.SSLError: unknown error (_ssl.c:2831)

how could i fix this..???
