### ISSUE TITLE
Failing basic start with connect_device_package on Raspbian

### ISSUE THREAD

**Issue by lthiery-molekule** [aws/aws-iot-device-sdk-python#42]
Hello,

I'm using a Raspberry Pi 3 Rev B - it's Internet appears to work just fine as a I can ping different servers, run updates, etc.

When I tried to run start.sh, I get the following problem:

```
Runing pub/sub sample application...
2017-04-17 18:55:27,030 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Paho MQTT Client init.
2017-04-17 18:55:27,031 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - ClientID: basicPubSub
2017-04-17 18:55:27,031 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Protocol: MQTTv3.1.1
2017-04-17 18:55:27,031 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Register Paho MQTT Client callbacks.
2017-04-17 18:55:27,032 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - mqttCore init.
2017-04-17 18:55:27,032 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load CAFile from: root-CA.crt
2017-04-17 18:55:27,032 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Key from: Louis-TestPi.private.key
2017-04-17 18:55:27,033 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Cert from: Louis-TestPi.cert.pem
2017-04-17 18:55:27,033 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: baseReconnectTime = 1 sec
2017-04-17 18:55:27,033 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: maximumReconnectTime = 32 sec
2017-04-17 18:55:27,033 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: minimumConnectTime = 20 sec
2017-04-17 18:55:27,034 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: queueSize = -1
2017-04-17 18:55:27,034 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: dropBehavior = Drop Newest
2017-04-17 18:55:27,034 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for draining interval: 0.5 sec
2017-04-17 18:55:27,035 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum connect/disconnect timeout to be 10 second.
2017-04-17 18:55:27,035 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum MQTT operation timeout to be 5 second
2017-04-17 18:55:27,036 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connection type: TLSv1.2 Mutual Authentication
Traceback (most recent call last):
  File "aws-iot-device-sdk-python/samples/basicPubSub/basicPubSub.py", line 133, in <module>
    myAWSIoTMQTTClient.connect()
  File "/usr/local/lib/python3.4/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 403, in connect
    return self._mqttCore.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python3.4/dist-packages/AWSIoTPythonSDK/core/protocol/mqttCore.py", line 290, in connect
    self._pahoClient.connect(self._host, self._port, keepAliveInterval)  # Throw exception...
  File "/usr/local/lib/python3.4/dist-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 655, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.4/dist-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 798, in reconnect
    ciphers=self._tls_ciphers)
  File "/usr/lib/python3.4/ssl.py", line 887, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.4/ssl.py", line 510, in __init__
    self._context.load_verify_locations(ca_certs)
ssl.SSLError: unknown error (_ssl.c:2736)
```

Any idea what's going on? I tried in Python 2.7 and have the exact same error message.

**Comment by hedeshianaws** [comment]
Hello,

Can you elaborate on this start.sh? How are you starting this sample application? Can you confirm what CA you are using? Are you using self-signed certificates?

**Comment by liuszeng** [comment]
Hi @lthiery-molekule ,

We have not heard from you for a while. We are closing the issue for now. If you have any further questions, please feel free to re-open this issue or start a new thread.

Thanks,
Liusu
