### ISSUE TITLE
MQTT callback is broken on 1.2.0

### ISSUE THREAD

**Issue by pickfire** [aws/aws-iot-device-sdk-python#69]
Hi, after the upgrade to 1.2.0 from 1.1.2, the `client` and `userdata` isn't passed to the callback as shown in https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L225

Or the issue might be raised because of https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L254 where the comment in the code mentioned that the message_callback could be None.

Example code:
```python
import json


def custom_callback(client, userdata, message):
    """Simple heartbeat callback."""
    if json.loads(message.payload.decode())['message'] == 'ping':
        client.publishAsync(message.topic, '{"message": "pong"}', 1)
```

**Comment by hedeshianaws** [comment]
Hello,

Thank your for reporting this issue. The line you pointed certainly looks suspicious: https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L254

Does your sample work if you uncomment that code?

**Comment by pickfire** [comment]
@hedeshianaws I tried changing back to the commented code but it doesn't work as well.
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/attendix/venv/lib/python3.4/site-packages/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 137, in _dispatch
    self._dispatch_one()
  File "/home/pi/attendix/venv/lib/python3.4/site-packages/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 142, in _dispatch_one
    self._dispatch_methods[event_type](mid, data)
  File "/home/pi/attendix/venv/lib/python3.4/site-packages/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 225, in _dispatch_message
    message_callback(client, userdata, message)
NameError: name 'client' is not defined
```

**Comment by hedeshianaws** [comment]
In your example, I see that you are not using client or userdata. Is this expected? It seems for whatever reason, we are intentionally throwing that data away. Likely since 'client' refers to the Paho client instance used by the SDK, and the user of the SDK is not supposed to 'know' about it. Unfortunately, since our Python SDK expert is unavailable, I can't comment on why that change was made (there is no documentation either).

You can try this patch if you would like:

```
diff --git a/AWSIoTPythonSDK/core/protocol/internal/workers.py b/AWSIoTPythonSDK/core/protocol/internal/workers.py
index 656578a..9c42385 100644
--- a/AWSIoTPythonSDK/core/protocol/internal/workers.py
+++ b/AWSIoTPythonSDK/core/protocol/internal/workers.py
@@ -34,32 +34,33 @@ class EventProducer(object):
         self._event_queue = event_queue
 
     def on_connect(self, client, user_data, flags, rc):
-        self._add_to_queue(FixedEventMids.CONNACK_MID, EventTypes.CONNACK, rc)
-        self._logger.debug("Produced [connack] event")
+        self._add_to_queue(FixedEventMids.CONNACK_MID, EventTypes.CONNACK, client, user_data, rc)
+        self._logger.debug("Produced [connack] event flags: %s rc: %s" % (str(flags), str(rc)))
 
     def on_disconnect(self, client, user_data, rc):
-        self._add_to_queue(FixedEventMids.DISCONNECT_MID, EventTypes.DISCONNECT, rc)
+        self._add_to_queue(FixedEventMids.DISCONNECT_MID, EventTypes.DISCONNECT, client, user_data, rc)
         self._logger.debug("Produced [disconnect] event")
 
     def on_publish(self, client, user_data, mid):
-        self._add_to_queue(mid, EventTypes.PUBACK, None)
+        self._add_to_queue(mid, EventTypes.PUBACK, client, user_data, None)
         self._logger.debug("Produced [puback] event")
 
     def on_subscribe(self, client, user_data, mid, granted_qos):
-        self._add_to_queue(mid, EventTypes.SUBACK, granted_qos)
+        self._add_to_queue(mid, EventTypes.SUBACK, client, user_data, granted_qos)
         self._logger.debug("Produced [suback] event")
 
     def on_unsubscribe(self, client, user_data, mid):
-        self._add_to_queue(mid, EventTypes.UNSUBACK, None)
+        self._add_to_queue(mid, EventTypes.UNSUBACK, client, user_data, None)
         self._logger.debug("Produced [unsuback] event")
 
     def on_message(self, client, user_data, message):
-        self._add_to_queue(FixedEventMids.MESSAGE_MID, EventTypes.MESSAGE, message)
+        self._add_to_queue(FixedEventMids.MESSAGE_MID, EventTypes.MESSAGE, client, user_data, message)
         self._logger.debug("Produced [message] event")
 
-    def _add_to_queue(self, mid, event_type, data):
+    def _add_to_queue(self, mid, event_type, client, user_data, data):
         with self._cv:
-            self._event_queue.put((mid, event_type, data))
+            self._logger.debug("Added to Q")
+            self._event_queue.put((mid, event_type, client, user_data, data))
             self._cv.notify()
@@ -137,9 +140,15 @@ class EventConsumer(object):
                         self._dispatch_one()
 
     def _dispatch_one(self):
-        mid, event_type, data = self._event_queue.get()
+        mid, event_type, client, user_data, data = self._event_queue.get()

         if mid:
-            self._dispatch_methods[event_type](mid, data)
+            self._dispatch_methods[event_type](mid, client, user_data, data)
             self._internal_async_client.invoke_event_callback(mid, data=data)
             # We need to make sure disconnect event gets dispatched and then we stop the consumer
             if self._need_to_stop_dispatching(mid):
@@ -150,7 +159,7 @@ class EventConsumer(object):
         return (ClientStatus.USER_DISCONNECT == status or ClientStatus.CONNECT == status) \
                and mid == FixedEventMids.DISCONNECT_MID
 
-    def _dispatch_connack(self, mid, rc):
+    def _dispatch_connack(self, mid, client, user_data, rc):
         status = self._client_status.get_status()
         self._logger.debug("Dispatching [connack] event")
         if self._need_recover():
@@ -197,7 +206,7 @@ class EventConsumer(object):
     def _has_user_disconnect_request(self):
         return ClientStatus.USER_DISCONNECT == self._client_status.get_status()
 
-    def _dispatch_disconnect(self, mid, rc):
+    def _dispatch_disconnect(self, mid, client, user_data, rc):
         self._logger.debug("Dispatching [disconnect] event")
         status = self._client_status.get_status()
         if ClientStatus.USER_DISCONNECT == status or ClientStatus.CONNECT == status:
@@ -207,22 +216,22 @@ class EventConsumer(object):
 
     # For puback, suback and unsuback, ack callback invocation is handled in dispatch_one
     # Do nothing in the event dispatching itself
-    def _dispatch_puback(self, mid, rc):
+    def _dispatch_puback(self, mid, client, user_data, rc):
         self._logger.debug("Dispatching [puback] event")
 
-    def _dispatch_suback(self, mid, rc):
+    def _dispatch_suback(self, mid, client, user_data, rc):
         self._logger.debug("Dispatching [suback] event")
 
-    def _dispatch_unsuback(self, mid, rc):
+    def _dispatch_unsuback(self, mid, client, user_data, rc):
         self._logger.debug("Dispatching [unsuback] event")
 
-    def _dispatch_message(self, mid, message):
+    def _dispatch_message(self, mid, client, user_data, message):
         self._logger.debug("Dispatching [message] event")
         subscriptions = self._subscription_manager.list_records()
         if subscriptions:
             for topic, (qos, message_callback) in subscriptions:
                 if topic_matches_sub(topic, message.topic) and message_callback:
-                    message_callback(None, None, message)  # message_callback(client, userdata, message)
+                    message_callback(client, user_data, message)


```

**Comment by pickfire** [comment]
@hedeshianaws Yup, that works.

**Comment by liuszeng** [comment]
Hi @pickfire ,

We have updated the documentation correspondingly in v1.3.1 release to call out the "client" and "userdata" change. Sorry again for the inconvenience it has caused.

Thanks,
Liusu
