### ISSUE TITLE
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'time'

### ISSUE THREAD

**Issue by morrissinger** [aws/aws-iot-device-sdk-python#72]
This occurs in the version of the code available at the v1.2.0 tag:

When running a very basic example to publish to a topic, there is a race condition that occurs where a thread may close before the client has terminated the connection. (At least, I think that's what is going on...)

As such, running the following code to drive the client can produce the error:

```python
# publish.py
import logging
import time
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

KEY_PATH = "./certs/"

host = "MYHOST.iot.us-east-1.amazonaws.com"
rootCAPath = KEY_PATH + "root-certificate.pem"
certificatePath = KEY_PATH + "cert.crt"
privateKeyPath = KEY_PATH + "private.pem.key"
clientId = "MYTHING"
topic = "MYTOPIC"

# Configure logging
logger = logging.getLogger("AWSIoTPythonSDK.core")
logger.setLevel(logging.DEBUG)
streamHandler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
streamHandler.setFormatter(formatter)
logger.addHandler(streamHandler)

# Init AWSIoTMQTTClient
myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
myAWSIoTMQTTClient.configureEndpoint(host, 8883)
myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

# AWSIoTMQTTClient connection configuration
myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1) # Infinite offline publishing queueingr
myAWSIoTMQTTClient.configureDrainingFrequency(2) # 2 Hz
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10) # 10 sec
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5) # % sec

# Connect
myAWSIoTMQTTClient.connect()
time.sleep(2)

# publish
myAWSIoTMQTTClient.publish(topic, "{\"message\": \"my message\"}", 0)
```

This code can produce the following traceback:

```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 757, in run
  File "/home/ec2-user/thing-topic-publisher-python/lib/aws-iot-device-sdk-python/AWSIoTPythonSDK/core/protocol/paho/client.py", line 2354, in _thread_main
  File "/home/ec2-user/thing-topic-publisher-python/lib/aws-iot-device-sdk-python/AWSIoTPythonSDK/core/protocol/paho/client.py", line 1326, in loop_forever
  File "/home/ec2-user/thing-topic-publisher-python/lib/aws-iot-device-sdk-python/AWSIoTPythonSDK/core/protocol/paho/client.py", line 889, in loop
  File "/home/ec2-user/thing-topic-publisher-python/lib/aws-iot-device-sdk-python/AWSIoTPythonSDK/core/protocol/paho/client.py", line 1183, in loop_misc
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'time'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 757, in run
  File "/home/ec2-user/thing-topic-publisher-python/lib/aws-iot-device-sdk-python/AWSIoTPythonSDK/core/protocol/internal/workers.py", line 137, in _dispatch
  File "/usr/lib64/python2.7/threading.py", line 289, in __exit__
  File "/usr/lib64/python2.7/threading.py", line 216, in __exit__
  File "/usr/lib64/python2.7/threading.py", line 203, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

NB: I installed the library locally in lib/aws-iot-device-sdk-python, which is why the output reflects this.

So, as we can see, this is a pretty bare-bones example.

I am able to fix the issue by adding a time.sleep(10) statement to the bottom of my `publish.py` file. Obviously 10 seconds is a bit impairing, but I wanted to be sure I could demonstrate the race.

Is there a way to modify the client to not require this? This would seem to be the fix to this race condition.

**Comment by khirstinova** [comment]
This looks like another open issue.  This is on shutdown but thankfully doesn't affect the exit code of the program.

**Comment by morrissinger** [comment]
@khirstinova, agreed. Specifically https://github.com/aws/aws-iot-device-sdk-python/issues/67. Closing my issue as a duplicate, but will provide a link back for future reference.

**Comment by CheetahGod** [comment]
This still is a problem

**Comment by CheetahGod** [comment]
This still is a problem
